### ISSUE TITLE
Can't connect to server at databases.pacha.dev

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#1011]
Only noticed because relational.fit also seems down.

``` r
dm:::dbedu_con()
#> Error: Failed to connect: Can't connect to server on 'databases.pacha.dev' (36)
```

<sup>Created on 2022-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

CC @pachadotdev.

**Comment by pachadotdev** [comment]
@krlmlr relational.fit is still down
![Screenshot from 2022-06-03 01-17-49](https://user-images.githubusercontent.com/10091065/171791097-a5a7b679-94bb-467e-9c34-3abae96a2a88.png)

I have checked the access and it should work now

**Comment by krlmlr** [comment]
Thanks. Unfortunately I'm still getting the same error.

**Comment by pachadotdev** [comment]
fixed !
sorry about it @krlmlr 
the postgresql instance in the same server has been working great, mysql got updated and altered the bind-address in 50-server.cnf
![Screenshot from 2022-06-03 01-29-38](https://user-images.githubusercontent.com/10091065/171792406-c104b566-7341-4396-ba0d-9ba3b95ec68b.png)

**Comment by pachadotdev** [comment]
yet one more point to love PostgreSQL over any other SQL backend!

**Comment by krlmlr** [comment]
Thanks, works for me now!

Postgres is solid, SQL Server is what everybody seems to use 🙃
