### ISSUE TITLE
Remove or deprecate rows_truncate() and dm_rows_truncate()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#1031]
These are DDL and require different permissions.

**Comment by krlmlr** [comment]
CC @IndrajeetPatil.

**Comment by IndrajeetPatil** [comment]
These will be removed or deprecated in favour of which function?

**Comment by krlmlr** [comment]
We want a way to scrap an existing data model before it's redeployed with `copy_dm_to()` . So far this step has been done manually, perhaps we could add a `dm_tables_delete()` that issues a `DROP TABLES` in the correct sequence and with an `in_place = FALSE` argument (and a message that you need to set it to `TRUE`).

**Comment by krlmlr** [comment]
We should deprecate the generic now.
