### ISSUE TITLE
Interactive creation of dm code

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#1076]
Since this morning we were questioning the way disentangling currently works, I was wondering if after all a small Shiny App wouldn't actually solve our problems.

The function starting the app would take one argument: the `dm` to disentangle.
The app has several elements:
1. Visual representation of the current state of the dm
2. A box with the code that can be copied to produce the current state of the `dm` from the input dm.
3. A "reset" button
4. An "undo last action" button
5. An info box that says one of: "Cycle detected" (red) or "Cycle-free" (green)
6. Four possible actions:
  - remove table (providing Dropdown menu with table list)
  - remove FK (providing Dropdown menu with FK list)
  - duplicate/multiply table (providing Dropdown menu with list of candidate tables for multiplication)
  - Current implementation of `dm_disentangle()`, taking a `start` table as an argument (providing Dropdown menu with table list); this one can only be used once, but the other three actions can still be used afterwards.

@moodymudskipper said he believes that people tend to prefer thinking about data models in a visual way, which I agree with. This approach would take this into account, plus, it's not very hard to implement. And we would give the user all the flexibility (and also responsibility) to create the cycle-free dm they want.

**Comment by krlmlr** [comment]
Good idea, I'm curious what the "duplicate/multiply table" operation looks like in general.

Should we budget a day for a prototype?

**Comment by TSchiefer** [comment]
One more thought: Maybe we shouldn't make it too sophisticated and with this operation really just add one copy of the table in question. 
If we do this via `dm_zoom_to() -> dm_insert_zoomed() (-> dm_rename_tbl()???)`, the FKs would be part of the new table and could be removed later on.

On the other hand, if we just add a copy of the table without the key info, we could in addition provide the option to add PKs and FKs in the Shiny App, potentially widening the range of the app's use cases.
We could also make it possible to rename and select tables in general in order to provide more flexibility.

**Comment by krlmlr** [comment]
How about "splitting a table" as an atomic operation -- create one copy for each incoming foreign key into the table, copy all outgoing foreign keys?

As discussed yesterday, an esquisse-like Shiny app to prepare a dm object might be a useful addition anyway, with support for much simpler operations such as table selection, column selection/reordering, key removal/creation, deconstruction, ... . Let's sketch out the operations we want to support (and the code that we generate for those operations) before implementing the app.

**Comment by TSchiefer** [comment]
> create one copy for each incoming foreign key into the table, copy all outgoing foreign keys

Sounds good, let's try. We could theoretically also export such a function, it could make sense in certain situations.

About the more general app: this is great, as discussed. Possibly it could be good though to be able to switch between two distinct toolsets for general "topics": one could be "Removing cycles", the other "dm manipulation" (or similar)? Otherwise it might be overwhelming to have everything available at once. Maybe not too important to decide at this point...

**Comment by TSchiefer** [comment]
FYI, with a tweak of the print method of one of these 2 it should work:
``` r
suppressPackageStartupMessages({
  library(dm)
  library(magrittr)
  library(gestalt)
})
dm_nyc <- dm_nycflights13(cycle = FALSE)
library(gestalt)

# with gestalt `CompositeFunction`
res_call_gestalt <- dm_rm_fk(flights, ref_table = airlines) %>>>% 
  dm_rm_pk(airlines)
res_call_gestalt
#> <Function Composition>
#> In order of application:
#> 
#> [[1]]
#>   function (..., . = ..1) 
#>   dm_rm_fk(., flights, ref_table = airlines)
#> 
#> [[2]]
#>   function (..., . = ..1) 
#>   dm_rm_pk(., airlines)
#> 
#> Recover the list of functions with 'as.list()'.
as.list(res_call_gestalt)
#> [[1]]
#> function (..., . = ..1) 
#> dm_rm_fk(., flights, ref_table = airlines)
#> 
#> [[2]]
#> function (..., . = ..1) 
#> dm_rm_pk(., airlines)
res_call_gestalt(dm_nyc)
#> Removing foreign keys: %>%
#>   dm_rm_fk(flights, carrier, airlines)
#> ── Metadata ────────────────────────────────────────────────────────────────────
#> Tables: `airlines`, `airports`, `flights`, `planes`, `weather`
#> Columns: 53
#> Primary keys: 3
#> Foreign keys: 3


# with magrittr `fseq`:
res_call <- . %>% 
  dm_rm_fk(flights, ref_table = airlines) %>% 
  dm_rm_pk(airlines)
res_call
#> Functional sequence with the following components:
#> 
#>  1. dm_rm_fk(., flights, ref_table = airlines)
#>  2. dm_rm_pk(., airlines)
#> 
#> Use 'functions' to extract the individual functions.
functions(res_call)
#> [[1]]
#> function (.) 
#> dm_rm_fk(., flights, ref_table = airlines)
#> 
#> [[2]]
#> function (.) 
#> dm_rm_pk(., airlines)
res_call(dm_nyc)
#> Removing foreign keys: %>%
#>   dm_rm_fk(flights, carrier, airlines)
#> ── Metadata ────────────────────────────────────────────────────────────────────
#> Tables: `airlines`, `airports`, `flights`, `planes`, `weather`
#> Columns: 53
#> Primary keys: 3
#> Foreign keys: 3
```

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by TSchiefer** [comment]
In {esquisse}, the function call is built in the function `esquisse::ggcall(data = NULL, mapping = NULL, geom = NULL, [etc...])`. 
It adds for each argument a new function call as an expression, e.g. `expr(!!ggcall + !!ylim)`. (ggcall is grown)

**Comment by krlmlr** [comment]
Cool! I suggest we stay with magrittr for now, because it's already imported. We should revisit gestalt if we start seeing limitations of the magrittr approach. It seems safest to create a small internal API (set of functions) that deals with plans that we want to execute and also print.

**Comment by krlmlr** [comment]
The next steps would be:

- implement one or two operations, e.g. "remove table" and "add foreign key"
- review
- add a very rough sketch for a Shiny app

We might get help with the Shiny app.

**Comment by krlmlr** [comment]
One operation we'll add once we have it is destructuring.

**Comment by TSchiefer** [comment]
> Do we need a slightly more flexible approach, perhaps combining simple calls and functional sequences?

Maybe we can adapt the internal API to support this once the need arises and start with functional sequences for now?

**Comment by christophsax** [comment]
I will seriously work on this from Sunday evening on.

**Comment by krlmlr** [comment]
Do we want to create individual issues for the remaining functionality?

**Comment by TSchiefer** [comment]
done: #1355, #1356, #1357, #1358, #1359
anything I forgot?
can this issue be closed?

**Comment by krlmlr** [comment]
Thanks, we can always add more.
