### ISSUE TITLE
Don't use deprecated functions in the tutorials

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/dm#1096]
Seen [here](https://cynkra.github.io/dm/dev/articles/howto-dm-copy.html).

<img width="1364" alt="Screenshot 2022-06-16 at 01 52 10" src="https://user-images.githubusercontent.com/11330453/173960937-e6d6a47e-b9f0-4bbb-9576-f613ccf8c2d3.png">

**Comment by krlmlr** [comment]
Good catch, we should avoid that. Should we do a full-text search for "deprecated" on the pkgdown site? At some point I'd like to add snapshot tests for the vignettes like in tibble.

**Comment by IndrajeetPatil** [comment]
Just did. The only other vignette where deprecated functions are used seems to be [this](https://cynkra.github.io/dm/dev/articles/tech-dm-class.html) one.

<img width="1324" alt="Screenshot 2022-06-16 at 07 53 54" src="https://user-images.githubusercontent.com/11330453/174001420-e21edb47-6cc9-45ec-8334-11848157c48b.png">

<img width="1020" alt="Screenshot 2022-06-16 at 07 54 10" src="https://user-images.githubusercontent.com/11330453/174001429-8c7852ca-1d3c-477a-9358-d535c4a0dc4c.png">

**Comment by IndrajeetPatil** [comment]
Another one [here](https://cynkra.github.io/dm/dev/articles/tech-dm-join.html)

![image](https://user-images.githubusercontent.com/11330453/174043943-8f808f79-b070-4a29-926d-d6777227dbf0.jpeg)

**Comment by krlmlr** [comment]
Done now?
