### ISSUE TITLE
Re-assess if section IDs are needed in vignettes

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/dm#1142]
As requested [here](https://github.com/cynkra/dm/pull/1132#discussion_r902184985).

**Comment by maelle** [comment]
@krlmlr or others, do you remember why section IDs were used in vignettes?

**Comment by IndrajeetPatil** [comment]
Sometimes they are used to refer to specific sections. Like here, e.g.:

https://github.com/cynkra/dm/blob/4496328276529a30f455bf55b82c282d15829e57/vignettes/howto-dm-theory.Rmd#L22-L28

**Comment by maelle** [comment]
Good catch. :pray: As pkgdown has an automatic TOC, and I suspect most readers read vignettes in pkgdown websites, I wonder whether this could/should be removed.

**Comment by IndrajeetPatil** [comment]
I think this goes beyond TOC.

In some [vignettes](https://github.com/cynkra/dm/blob/main/vignettes/tech-dm-class.Rmd), different sections are heavily interlinked via IDs, so we can definitely not remove these section IDs without worsening the quality of interlinking in these vignettes.

For example,

https://github.com/cynkra/dm/blob/0956cf0021b19f19ad62667ac42c6ddc8a8e1c1c/vignettes/tech-dm-class.Rmd#L132

https://github.com/cynkra/dm/blob/0956cf0021b19f19ad62667ac42c6ddc8a8e1c1c/vignettes/tech-dm-class.Rmd#L237

etc.
