### ISSUE TITLE
What should the middleware look like?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#1152]
@christophsax floated the idea of a "state object" which I am now beginning to like.

If we can capture the entire state of the Shiny application in an immutable object (nested list?), we can define operations on that state (as pure functions that return a modified state object), and also query the possible UI options. This seems a bit more versatile than `enum_ops()` .

What is the state of our app?

- dm object (as a quosure and perhaps evaluated)
- list of calls already defined
- selected table
- selected column(s)

Anything else?

**Comment by krlmlr** [comment]
The existing `enum_ops()` targets a wizard-style app, where the user is guided through the available options at each step. A state object might allow for a more flexible user interface?

**Comment by christophsax** [comment]
I try to deploy a mockup app later today that gives an idea of the expected frontend.

**Comment by krlmlr** [comment]
The app looks good, thanks! We need to think about how to proceed with the middleware, and what the best options for an interactive diagram are.

**Comment by krlmlr** [comment]
Code moved elsewhere.
