### ISSUE TITLE
Clickable elements with `dm_draw()`

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#1153]
We might be able to support clickable links without hacking the `.svg` file. For the following input:

```graphviz
digraph G {
    bgcolor="transparent";
    fontname="Helvetica";
    node [fontname="Helvetica"];

    b0 [URL="https://google.com"]
	b0 -> b1;
}
```

the following output is produced:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: G Pages: 1 -->
<svg width="62pt" height="116pt"
 viewBox="0.00 0.00 62.00 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<!-- b0 -->
<g id="node1" class="node">
<title>b0</title>
<g id="a_node1"><a xlink:href="https://google.com" xlink:title="b0">
<ellipse fill="none" stroke="#000000" cx="27" cy="-90" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-85.8" font-family="Helvetica,sans-Serif" font-size="14.00" fill="#000000">b0</text>
</a>
</g>
</g>
<!-- b1 -->
<g id="node2" class="node">
<title>b1</title>
<ellipse fill="none" stroke="#000000" cx="27" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-13.8" font-family="Helvetica,sans-Serif" font-size="14.00" fill="#000000">b1</text>
</g>
<!-- b0&#45;&gt;b1 -->
<g id="edge1" class="edge">
<title>b0&#45;&gt;b1</title>
<path fill="none" stroke="#000000" d="M27,-71.8314C27,-64.131 27,-54.9743 27,-46.4166"/>
<polygon fill="#000000" stroke="#000000" points="30.5001,-46.4132 27,-36.4133 23.5001,-46.4133 30.5001,-46.4132"/>
</g>
</g>
</svg>
```

@christophsax: Can we change the URL in a way that clicking the node can be captured by the Shiny app if the SVG is displayed there in an `uiOutput()` ?

See http://viz-js.com/ for a playground.

**Comment by christophsax** [comment]
You mean like this? It will reload the session, so I don't think we want to do this.

```r
  shinyApp(
    ui = fluidPage(
      textInput("txt", "Enter new query string"),
      helpText("Format: ?param1=val1&param2=val2"),
      actionButton("go", "Update"),
      hr(),
      verbatimTextOutput("query")
    ),
    server = function(input, output, session) {
      observeEvent(input$go, {
        updateQueryString(input$txt, mode = "push")
      })
      output$query <- renderText({
        query <- getQueryString()
        queryText <- paste(names(query), query,
                       sep = "=", collapse=", ")
        paste("Your query string is:\n", queryText)
      })
    }
  )
```

https://rdrr.io/cran/shiny/man/getQueryString.html

**Comment by christophsax** [comment]
An interactive JS visualization tool may support this out of the box and seems a more obvious solution to me.

**Comment by krlmlr** [comment]
Happy to review other visualization backends.

For now, a few more links, it seems that we can use `onclick="<js code>"` in SVG. Would that work with Shiny?

- https://forum.graphviz.org/t/can-i-make-a-digraph-node-interactive/503
- https://forum.graphviz.org/t/highlight-edge-and-attached-nodes-on-click/605

Postprocessing the SVG shouldn't be that difficult.

**Comment by krlmlr** [comment]
Can you please take a look? Try also clicking the "airlines" table.

https://jsfiddle.net/u02a8kdn/61/

What should we fill in in the `onclick` handlers so that you can pick it up from Shiny? https://shiny.rstudio.com/articles/js-send-message.html, scenario 2?

We should be able to highlight the selected elements too, perhaps with JavaScript? I couldn't adapt https://css-tricks.com/click-svg-to-focus/ to my needs, though.

https://stackoverflow.com/a/70366061/946850 suggests using the panzoom JS library for panning and zooming.

**Comment by krlmlr** [comment]
Note that this requires using an `uiOutput()` that contains the SVG as created by `DiagrammeRsvg::export_svg()` .

**Comment by benubah** [comment]
> What should we fill in in the onclick handlers so that you can pick it up from Shiny? https://shiny.rstudio.com/articles/js-send-message.html, scenario 2?
>

`Shiny.onInputChange(element_id, value_to_be_sent_to_shiny)`

>We should be able to highlight the selected elements too, perhaps with JavaScript? I couldn't adapt https://css-tricks.com/click-svg-to-focus/ to my needs, though.
>

Take a look here: https://jsfiddle.net/r43tapco/

**Comment by krlmlr** [comment]
Lovely! 

- We also need multi-select.
- How can we combine highlighting on hover and highlighting on selection?
- Do we need to inject the JavaScript and CSS into the SVG file? Or can we also provide it externally?

**Comment by krlmlr** [comment]
Beautiful! One last nit: can we also make the arrow heads a bit bolder when hovering?

I'll follow up with a more detailed specification of what we want to achieve here.

**Comment by benubah** [comment]
> One last nit: can we also make the arrow heads a bit bolder when hovering?

Yes, https://jsfiddle.net/r43tapco/8/

**Comment by krlmlr** [comment]
It seems we want to use {svgPanZoom} to render the SVG. Will we still be able to use the JavaScript and CSS code?

(This renders statically in a reprex, but when run locally it will do what it says on the tin.)

``` r
library(conflicted)
library(dm)

dm_nycflights13() %>%
  dm_draw(graph_attrs = 'bgcolor="transparent"', node_attrs = 'fontname="Helvetica"') %>%
  DiagrammeRsvg::export_svg() %>%
  svgPanZoom::svgPanZoom()
```

![](https://i.imgur.com/nPIvmGo.png)

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by benubah** [comment]
Yes, this is now being take care in another development
