### ISSUE TITLE
Named arguments to successive enum_ops() calls are not overridden

### ISSUE THREAD

**Issue by egnha** [cynkra/dm#1154]
Presently, the following `enum_ops()` call is erroring:
https://github.com/cynkra/dm/blob/0956cf0021b19f19ad62667ac42c6ddc8a8e1c1c/scratch/code_generation_middleware_2.R#L59-L67
The problem is a name clash: Both `ops_3$input` and `user_choice_3` have a component named `column_names`.

More than one fix is possible. (Change `enum_ops()`? Doctor the call?) The context here doesn't suggest what is right/intended.

Cf. https://github.com/cynkra/dm/issues/1150#issuecomment-1162858354_

**Comment by egnha** [comment]
Yes, I think it makes sense to simplify `enum_ops()`, esp. as preparation for its extension to additional op-names (e.g., `"dm_add_fk"`, `"dm_rm_pk"`, etc.). I could try work on that.

**Comment by egnha** [comment]
I'll work out a simplification of `enum_ops()`.

**Comment by egnha** [comment]
I will fill in the details and test against the snapshot tests (tomorrow). PR TBD.

**Comment by egnha** [comment]
I feel the same way. However, the `local()` is specifically here to constrain name-lookup. I think that legitimizes its use.

**Comment by egnha** [comment]
> Thanks. This might work, should we take a look at what this looks like in practice?

Sure, I'll fill in the elided parts tomorrow. (Essentially, a copy-paste of the branching logic, no new idea vis-à-vis code structure.)

**Comment by egnha** [comment]
> If we need to constrain, could we switchpatch too?

Sorry, I don't quite understand this question. Could you elaborate, please?

**Comment by egnha** [comment]
Could this remark help: `enum()` is basically a `get()`. The `get()` has to be constrained—there is a fixed set of allowed `dm_*` operations.

**Comment by krlmlr** [comment]
I believe I see what it does. I just don't particularly like it. All those functions inside the `local()` need to be also accessible via direct function call. The same results could also be achieved with a fixed prefix or suffix that is only used for those functions, and we could add a snapshot test for those.

Switchpatching would be something like the following, if I understand that term correctly:

```r
switch(op,
  dm_add_pk = op_dm_add_pk,
  dm_add_fk = op_dm_add_fk,
  ...
)
```

**Comment by egnha** [comment]
I see what you mean. Something like that could also work.
