### ISSUE TITLE
Enable additional operators for enum_ops()

### ISSUE THREAD

**Issue by egnha** [cynkra/dm#1165]
Points 7 and 8 of https://github.com/cynkra/dm/issues/1076#issuecomment-1154887556 are not yet implemented. This issue sketches a possible implementation via an extension of `enum_ops()`. (Though in view of #1152, perhaps this is moot … ?)

Presently, `enum_ops()` can generate `dm_add_pk()` calls via the `op_name` argument value `"dm_add_pk"`. It remains to do the same for `dm_add_fk()`, and the removal operations `dm_rm_pk()` and `dm_rm_fk()`. Here are some initial steps in that direction.

Firstly, the additional operator cases are to be handled by the dispatcher [`enum()`](https://github.com/cynkra/dm/blob/f097e28636ca4b3be10966dbb27971acb38050e6/R/enum_ops.R#L56-L60):

```R
enum <- function(op) {
  switch(op,
         dm_add_pk = enum_ops_dm_add_pk,
         # The following cases are to be added:
         dm_add_fk = enum_ops_dm_add_fk,
         dm_rm_pk = enum_ops_dm_rm_pk,
         dm_rm_fk = enum_ops_dm_rm_fk)
}
```

Secondly, it appears the newly added functions `enum_ops_dm_add_fk()`, etc., can be modeled after the presently implemented [`enum_ops_dm_add_pk()`](https://github.com/cynkra/dm/blob/f097e28636ca4b3be10966dbb27971acb38050e6/R/enum_ops.R#L62-L73), like so:

```R
# Not 100% sure this is adequate, since I don't exactly know what the downstream Shiny app expects.

enum_ops_dm_add_fk <- function(dm, tbls, cols) {
  stopifnot(length(tbls) == 2)
  tbls <- syms(tbls)
  cols <- if (length(cols) == 1) sym(cols) else expr(c(!!!syms(cols)))
  list(call = expr(dm_add_fk(., !!tbls[[1]], !!cols, !!tbls[[2]])))
}

enum_ops_dm_rm_pk <- function(dm, tbls, cols) {
  stopifnot(length(tbls) == 1)
  tbls <- syms(tbls)
  cols <- if (length(cols) == 1) sym(cols) else expr(c(!!!syms(cols)))
  list(call = expr(dm_rm_pk(., !!tbls, !!cols)))
}

# NB. Virtually identical to enum_ops_dm_add_fk()
enum_ops_dm_rm_fk <- function(dm, tbls, cols) {
  stopifnot(length(tbls) == 2)
  tbls <- syms(tbls)
  cols <- if (length(cols) == 1) sym(cols) else expr(c(!!!syms(cols)))
  list(call = expr(dm_rm_fk(., !!tbls[[1]], !!cols, !!tbls[[2]])))
}
```

Thirdly, it looks like the internal function [`add_single(op, dm, tbls, cols)`](https://github.com/cynkra/dm/blob/f097e28636ca4b3be10966dbb27971acb38050e6/R/enum_ops.R#L19-L34) would need to be extended to the case where the operator name `"dm_rm_pk"` can be inferred from the argument values `dm`, `tbls`, `cols`. (For lack of time, I haven't figured out how that must be done …)

**Comment by krlmlr** [comment]
Thanks. A pull request would be great. The Shiny app can adapt, or perhaps we adapt the implementation here which is easy if we have tests.

I don't think we need to infer operator names from arguments, #1152.

**Comment by krlmlr** [comment]
Code moved elsewhere.
