### ISSUE TITLE
Chaining join operations

### ISSUE THREAD

**Issue by ratnanil** [cynkra/dm#1185]
I'm not sure if I should ask this here or rather on SO, I'll try it here first.

This is similar to the question [I tweeted](https://twitter.com/NRatnaweera/status/1538823695833120769) recently. To illustrate my question I'll use the tables `loans`, `accounts` and `districts` from `dm_financial`.

```
dm_financial2 <- dm_financial() %>% 
  dm_select_tbl(loans, accounts, districts)

dm_draw(dm_financial2)
```

![image](https://user-images.githubusercontent.com/12532091/177088530-0f66fd96-92a0-405e-8b6e-d32af7f9e6be.png)

As @krlmlr [suggested](https://twitter.com/cynkra_com/status/1538915803860443136), `dm_squash_to_tbl(dm_financial2, loans)` squashes / flattens all tables recursively, so that the `district` information is available in the output. My question: is there a way to achieve this result by chaining `join` commands? This would be very helpful, since for large databases `dm_squash_to_tbl` creates _very_ wide tables. 

The following does not work, since `loans` and `districts` are not directly linked by a foreign key relation.

```
dm_financial2 %>%
  dm_zoom_to(loans) %>%
  left_join(accounts) %>% 
  left_join(districts)
```

```
Error in `abort_tables_not_neighbors()`:
! Tables `loans` and `districts` are not directly linked by a foreign key relation.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by TSchiefer** [comment]
You can supply the `by` argument, in this case:
```
dm_financial2 %>%
  dm_zoom_to(loans) %>%
  left_join(accounts) %>% 
  left_join(districts, by = c("district_id" = "id"))
```

If you want to focus on specific columns in the joined table to prevent the resulting table to get too wide, you can in addition add a `select` argument, e.g.:
```
dm_financial2 %>%
  dm_zoom_to(loans) %>%
  left_join(accounts) %>% 
  left_join(districts, by = c("district_id" = "id"), select = c(A2, A3))
```

**Comment by ratnanil** [comment]
This package continuously amazes me... great work!!
