### ISSUE TITLE
Could flatten and squash be the same function with a different argument?

### ISSUE THREAD

**Issue by maelle** [cynkra/dm#1272]
Something like `dm_flatten_to_tbl(recursive = TRUE)`

**Comment by maelle** [comment]
the reason for my asking is that I was wondering whether it would make it easier to remember which code does what thing. :-)

**Comment by krlmlr** [comment]
Good point, perhaps worth considering before stable release.

@TSchiefer: Do you remember why we went for two functions?

**Comment by TSchiefer** [comment]
Maëlle asked me the same thing :)
I think it had something to do with being in line with `rlang::flatten()` and `rlang::squash()`. 
But I feel the `recursive` argument to `dm_flatten_to_tbl()` is way more intuitive.
