### ISSUE TITLE
Use dm_mutate_tbl()?

### ISSUE THREAD

**Issue by maelle** [cynkra/dm#1296]
Using #1294 for the cheatsheet I feel like

```
dm_tbl <- dm_select_tbl(dm1, -table1)
dm1 <- dm(dm1, table1 = table1_changed)
```

could be 

```
dm <- dm_mutate_tbl(table1 = table1_changed)
```

Is it not because `dm_mutate_tbl()` is experimental?

**Comment by maelle** [comment]
Oh I see "For now, the column names must be identical." in the docs

**Comment by krlmlr** [comment]
No action needed here.
