### ISSUE TITLE
error in dm_gui()

### ISSUE THREAD

**Issue by maelle** [cynkra/dm#1344]
Before running `pak::pak()` the code below had an uninformative error

```r
> dm::dm_gui()
Erreur dans `$<-.data.frame`(`*tmp*`, "call_text", value = c("dm::dm_gui()",  : 
  le tableau de remplacement a 4 lignes, le tableau remplacé en a 2
Backtrace:
  1. dm::dm_gui()
  6. dm (local) `<fn>`(...)
  7. rlang::abort(message)
       at dm/R/check_suggested.R:43:6
  8. rlang:::signal_abort(cnd, .file)
     ...
 10. rlang:::format_onerror_backtrace(orig, opt = backtrace_on_error)
 15. rlang:::format.rlang_trace(trace, simplify = simplify, max_frames = max_frames)
 16. rlang:::trace_format_branch(x, max_frames, dir, srcrefs)
 17. rlang:::trace_as_tree(trace, dir = dir, srcrefs = srcrefs)
 19. base::`$<-.data.frame`(`*tmp*`, "call_text", value = `<chr>`)
 ```

so I suspect there's some minimal dependency version needed somewhere? Now i get an informative error for that same code.

**Comment by krlmlr** [comment]
I replaced the compound `check_suggested()` call to individual calls in the cran-1.0.0 branch, does that work better when you uninstall several of those suggested deps?

**Comment by maelle** [comment]
oooh I was installing from main :woman_facepalming:

**Comment by maelle** [comment]
but in any case the error above was before I updated dependencies so I will not be able to reproduce it, we can probably close, someone who gets this error would see the fix is to run `pak::pak()` or an equivalent.
