### ISSUE TITLE
optimize performance `copy_dm_to()` for SQL Server

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#1383]
with dm v0.2.6:
``` r
library(tibble)
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(FBEA)
packageVersion("dm")
#> [1] '0.2.6'

con <- connect_to_db(database = "tobias")
t <- tibble(a = 1:100000, b = letters[((a - 1) %% 26) + 1], c = LETTERS[26 - ((a - 1) %% 26)])

dm_t <- dm(t)
system.time(res_dm_1 <- copy_dm_to(con, dm_t))
#>    user  system elapsed 
#>   0.206   0.033   2.154
```

<sup>Created on 2022-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

with dm v1.0.1.9000:
``` r
library(tibble)
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(FBEA)
packageVersion("dm")
#> [1] '1.0.1.9000'

con <- connect_to_db(database = "tobias")
t <- tibble(a = 1:100000, b = letters[((a - 1) %% 26) + 1], c = LETTERS[26 - ((a - 1) %% 26)])

dm_t <- dm(t)
system.time(res_dm_1 <- copy_dm_to(con, dm_t))
#>    user  system elapsed 
#>   1.046   0.052  12.492
```

<sup>Created on 2022-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Under certain circumstances we might need the newer approach, but maybe we can use an approach with higher performance by default.

**Comment by krlmlr** [comment]
The default will be safe approach that just works, and even may be limiting the size of the tables it can process. For performance, the loading must be performed in another way, outside of dm's control, using the new `dm_ddl_pre()` and `dm_ddl_post()` .
