### ISSUE TITLE
`dm_from_con()` should accept multiple schemas

### ISSUE THREAD

**Issue by mgirlich** [cynkra/dm#1441]
Currently, only one schema is accepted. 

```r
dm::dm_from_con(
  con,
  schema = c("a", "b")
)

#> Error in `abort_parameter_not_correct_length()`:
#> ! Parameter `schema` needs to be of length `1` but is of length 2 (`a`, `b`).
```

In my case I want to create a dm for two schemas (public + another one).

**Comment by krlmlr** [comment]
Thanks. Do you have foreign keys between tables in those schemas, does that work in Postgres?

**Comment by mgirlich** [comment]
We don't really use foreign keys (performance...) but I just tested it and it works fine.
