### ISSUE TITLE
Warnings with CRAN version of `{tidyselect}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/dm#1643]
A number of functions are generating these warnings (I saw them while running tests in `test-primary-keys.R`):

```r
Using an external vector in selections was deprecated in tidyselect 1.1.0.
i Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(x)

  # Now:
  data %>% select(all_of(x))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
```

**Comment by krlmlr** [comment]
Do these warnings show when running all tests? How to replicate?

**Comment by IndrajeetPatil** [comment]
Can't reproduce this anymore. It's possible that the warnings were coming from some other package which was loaded when I was running the tests.
