### ISSUE TITLE
All code chunks in "Get Started" vignettes are showing errors for release version of the website

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/dm#1647]
cf. https://cynkra.github.io/dm/articles/dm.html

<img width="815" alt="Screenshot 2022-10-20 at 20 53 50" src="https://user-images.githubusercontent.com/11330453/197033777-e47cd80e-7d93-4d79-ba52-c6eb4216368d.png">

<img width="812" alt="Screenshot 2022-10-20 at 20 53 58" src="https://user-images.githubusercontent.com/11330453/197033774-e5d8df23-0972-4cf9-9f04-1b105958ebcb.png">

etc.

**Comment by krlmlr** [comment]
Should be good in a few minutes from now.
