### ISSUE TITLE
Implement nest_join() for zoomed dm-s

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#168]
Only local data frames for now.

``` r
library(tidyverse)
library(dm)

cdm_nycflights13() %>%
  cdm_zoom_to_tbl(airlines) %>%
  nest()
#> # A tibble: 16 x 3
#>    carrier name                                   data
#>    <chr>   <chr>                       <list<df[,18]>>
#>  1 UA      United Air Lines Inc.         [58,665 × 18]
#>  2 AA      American Airlines Inc.        [32,729 × 18]
#>  3 B6      JetBlue Airways               [54,635 × 18]
#>  4 DL      Delta Air Lines Inc.          [48,110 × 18]
#>  5 EV      ExpressJet Airlines Inc.      [54,173 × 18]
#>  6 MQ      Envoy Air                     [26,397 × 18]
#>  7 US      US Airways Inc.               [20,536 × 18]
#>  8 WN      Southwest Airlines Co.        [12,275 × 18]
#>  9 VX      Virgin America                 [5,162 × 18]
#> 10 FL      AirTran Airways Corporation    [3,260 × 18]
#> 11 AS      Alaska Airlines Inc.             [714 × 18]
#> 12 9E      Endeavor Air Inc.             [18,460 × 18]
#> 13 F9      Frontier Airlines Inc.           [685 × 18]
#> 14 HA      Hawaiian Airlines Inc.           [342 × 18]
#> 15 YV      Mesa Airlines Inc.               [601 × 18]
#> 16 OO      SkyWest Airlines Inc.             [32 × 18]
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TSchiefer** [comment]
I have a working implementation `nest.zoomed_dm(.data, ...)`. When left empty, the ellipsis defaults to all child tables of the originally zoomed table. If tables are provided in the ellipsis though, I want 

1. the user to be able to choose the child tables he wants to nest
1. the user to choose the order in which the tables are nest-joined

These two points don't work though because of the way that `tidyr::nest()` is implemented:
```r
> nest
function (.data, ..., .key = deprecated()) 
{
    cols <- enquos(...)
    if (any(names2(cols) == "")) {
        col_names <- unname(tidyselect::vars_select(tbl_vars(.data), 
            !!!cols))
        cols_expr <- expr(c(!!!syms(col_names)))
        .key <- if (missing(.key)) 
            "data"
        else as.character(ensym(.key))
        cols <- quos(`:=`(!!.key, !!cols_expr))
        warn(paste0("All elements of `...` must be named.\n", 
            "Did you want `", .key, " = ", expr_text(cols_expr), 
            "`?"))
        return(nest(.data, !!!cols))
    }
    UseMethod("nest")
}
<bytecode: 0x7fdbf1c58120>
<environment: namespace:tidyr>
```
Problem is, that we have an implementation for `tbl_vars.zoomed_dm()` which outputs the columns of the zoomed table and not the tables of the `dm`.

So I thought, maybe better make a method for `dplyr::nest_join()` (in the end, nest-joins are what is happening). PR coming up.

**Comment by krlmlr** [comment]
`nest_join()` requires a `y` table which the operation currently doesn't implement. Need to revisit.

**Comment by TSchiefer** [comment]
> `nest_join()` requires a `y` table which the operation currently doesn't implement. Need to revisit.

I am not sure what you mean: For `nest_join.zoomed_dm(x, ...)` you can give one or more y-tables in the `...`

**Comment by TSchiefer** [comment]
Ok, I see what you mean...

**Comment by TSchiefer** [comment]
What about `nest_join.zoomed_dm(x, y = NULL, ...)` and whenever `y` is not `NULL` we throw an error?

**Comment by krlmlr** [comment]
Let's revisit this in a few weeks.

**Comment by krlmlr** [comment]
Wrapping and unwrapping seems much more powerful, closing for now.
