### ISSUE TITLE
Adding all columns into a box in data model visual

### ISSUE THREAD

**Issue by sound118** [cynkra/dm#1683]
Thanks for the great "dm" package. I am wondering if we could put all columns in one table into a box like what we could in 'datamodelR' package visual.

**Comment by TSchiefer** [comment]
Not sure if I understand correctly, but would this solve your problem?
``` r
suppressPackageStartupMessages(library(dm))
dm_nycflights13() %>% dm_draw(view_type = "all")
```

![](https://i.imgur.com/dY4O4K0.png)

<sup>Created on 2022-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sound118** [comment]
Thanks, this is what I meant to say. Nice!
