### ISSUE TITLE
Regarding data frame column type change in DM visual

### ISSUE THREAD

**Issue by sound118** [cynkra/dm#1684]
Hi, I got a question about dm_draw function "column_type" parameter. When we put it as "TRUE", it shows the data types for all columns in a data frame. However, once I make a change to one of the column types and rerun dm_draw function. The column type change is not revealed in the visual. A simple R script demo is as following:
library(nycflights13)

sapply(flights, class) #to show all column types in flights data frame

class(flights$dep_time) <- "timestamp without timezone" #make a change to dep_time column type from 'Date' to 'timestamp without timezone
'
library(dm)

dm_nycflights13() %>% dm_draw(view_type = "all", column_types = T) #Check to see if the column type change can be revealed

**Comment by TSchiefer** [comment]
Thanks, your example would work, if the altered table was used in the dm. Actually, in the function `dm_nycflights13()`, the `flights` table is supplied via `nycflights13::flights` (you can check the function definition by calling `dm_nycflights13` without braces in the console), so it will always use the table as it is defined in the {nycflights13} package.

You could make it work here like this:
``` r
library(dm)

as_timestamp_without_timezone <- function(x) {
  class(x) <- "timestamp without timezone"
  x
}
nyc_dm <- dm_nycflights13() %>% 
  dm_zoom_to(flights) %>% 
  mutate(dep_time = as_timestamp_without_timezone(dep_time)) %>% 
  dm_update_zoomed()
sapply(nyc_dm$flights, class)
#> $year
#> [1] "integer"
#> 
#> $month
#> [1] "integer"
#> 
#> $day
#> [1] "integer"
#> 
#> $dep_time
#> [1] "timestamp without timezone"
#> 
#> $sched_dep_time
#> [1] "integer"
#> 
#> $dep_delay
#> [1] "numeric"
#> 
#> $arr_time
#> [1] "integer"
#> 
#> $sched_arr_time
#> [1] "integer"
#> 
#> $arr_delay
#> [1] "numeric"
#> 
#> $carrier
#> [1] "character"
#> 
#> $flight
#> [1] "integer"
#> 
#> $tailnum
#> [1] "character"
#> 
#> $origin
#> [1] "character"
#> 
#> $dest
#> [1] "character"
#> 
#> $air_time
#> [1] "numeric"
#> 
#> $distance
#> [1] "numeric"
#> 
#> $hour
#> [1] "numeric"
#> 
#> $minute
#> [1] "numeric"
#> 
#> $time_hour
#> [1] "POSIXct" "POSIXt"
```

<sup>Created on 2022-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sound118** [comment]
Awesome, that works!

**Comment by sound118** [comment]
@TSchiefer hi, any suggestion for above raised issue.?

**Comment by TSchiefer** [comment]
Sorry for the late answer.
I generally think, not everything needs to be done within a `dm` object. You could work around doing the following:
``` r
suppressPackageStartupMessages({
  library(tibble)
  library(purrr)
  library(dplyr)
  library(dm)
})

df1 <- data.frame(
  id = c('122','345', '43'),
  name = c('john','matt','roger'),
  race = c('1','2','1'),
  age = c('20','23','34'),
  height = c('6.4', '5.7', '4.9'),
  stringsAsFactors = FALSE
)

cols <- data.frame(
  name = c('id','name', 'race', 'age', 'height'),
  type = c('varchar(20)', 'varchar(200)', 'varchar(10)', 'int', 'numeric(3,1)'),
  stringsAsFactors = FALSE) %>% 
  deframe()

# now a named character vector
cols
#>             id           name           race            age         height 
#>  "varchar(20)" "varchar(200)"  "varchar(10)"          "int" "numeric(3,1)"

df2 <- imap(df1, function(col, colname) {
  class(col) <- cols[[colname]]
  col
}) %>% 
  bind_cols()

df2
#> # A tibble: 3 × 5
#>   id         name       race       age   height    
#>   <vrch(20)> <vrc(200)> <vrch(10)> <int> <nmr(3,1)>
#> 1 122        john       1          20    6.4       
#> 2 345        matt       2          23    5.7       
#> 3 43         roger      1          34    4.9
map_chr(df2, class)
#>             id           name           race            age         height 
#>  "varchar(20)" "varchar(200)"  "varchar(10)"          "int" "numeric(3,1)"

dm(df2)
#> ── Metadata ────────────────────────────────────────────────────────────────────
#> Tables: `df2`
#> Columns: 5
#> Primary keys: 0
#> Foreign keys: 0
```

<sup>Created on 2022-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
