### ISSUE TITLE
remove all associated FKs with dm_rm_pk()/dm_rm_uk()

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#1729]
left to do after https://github.com/cynkra/dm/pull/1716, see https://github.com/cynkra/dm/pull/1716#pullrequestreview-1232180587

Once this is implemented, the disabled tests need to be reactivated and snapshots need to be updated.

**Comment by krlmlr** [comment]
No longer relevant, we keep the concept of implicit unique keys for now.
