### ISSUE TITLE
Feature Request: Allow multiple schema in `dm_from_con`

### ISSUE THREAD

**Issue by carlganz** [cynkra/dm#1770]
Sorry for another issue. I am working with a Star Schema datawarehouse, and the FACT tables are in a Schema named FACT and the related DIM tables are in a schema named DIM. What is the recommended way to use `dm` for Star Schemas?

Using multiple schema did not work as expected `dm_from_con(con, learn_keys = FALSE, schema = c("FACT", "DIM"))`, but I think updating [this line of code](https://github.com/cynkra/dm/blob/main/R/db-helpers.R#L153) to use `%in%` might work.

**Comment by krlmlr** [comment]
Thanks. Can you clone the repository and check if this change works for you? There also might be a pull request that's dealing with the issue.

**Comment by carlganz** [comment]
Yep #1534 seems to address it. I tried changing the one line [here](https://github.com/carlganz/dm), and it worked as expected
