### ISSUE TITLE
dm should use `dbplyr::in_catalog()` or `DBI::Id()` for dbplyr tables

### ISSUE THREAD

**Issue by mgirlich** [cynkra/dm#1788]
For joins dbplyr needs to get the table name. By using `ident_q()` dbplyr assumes the table is called `<catalog>.<schema>.<table>` instead of `<table>`. This leads to ugly queries (and might cause issues in some cases).

**Comment by mgirlich** [comment]
Sorry for the late feedback. It does indeed affect how the queries look. After https://github.com/tidyverse/dbplyr/pull/1284 is merged the queries will look something like:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

# using `ident_q()`
lf_x <- lazy_frame(id = 1, x = 1, .name = ident_q("schema.x"))
#> ℹ Using `ident_q()` for a table identifier is intended as fallback in case of
#>   bugs.
#> ℹ If you need it to work around a bug please open an issue
#>   <https://github.com/tidyverse/dbplyr/issues>.
#> This message is displayed once every 8 hours.
lf_y <- lazy_frame(id = 1, y = 1, .name = ident_q("schema.y"))
left_join(lf_x, lf_y, by = "id")
#> <SQL>
#> SELECT `LHS`.*, `y`
#> FROM schema.x AS `LHS`
#> LEFT JOIN schema.y AS `RHS`
#>   ON (`LHS`.`id` = `RHS`.`id`)

# using `in_schema()`
lf2_x <- lazy_frame(id = 1, x = 1, .name = in_schema("schema", "x"))
lf2_y <- lazy_frame(id = 1, y = 1, .name = in_schema("schema", "y"))
left_join(lf2_x, lf2_y, by = "id")
#> <SQL>
#> SELECT `x`.*, `y`
#> FROM `schema`.`x`
#> LEFT JOIN `schema`.`y`
#>   ON (`x`.`id` = `y`.`id`)
```

<sup>Created on 2023-05-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Also note that we plan to basically deprecate using `ident_q()`. It is only meant as a fallback in case of bugs.
The PR mentioned above helps us a lot to get rid of/avoid many subtle bugs with `in_schema()` etc.

According to https://github.com/tidyverse/dbplyr/issues/1099 this also has the advantage that we can send a `DBI::Id()` object to `DBI::dbWriteTable()`.

**Comment by krlmlr** [comment]
There remains just a single use of `ident_q()` in the tests, perhaps due to a merge conflict.
