### ISSUE TITLE
Saving & restoring the DM to new DB connection

### ISSUE THREAD

**Issue by systemnova** [cynkra/dm#1827]
Thanks for creating such an interesting & powerful package!
I was wondering if there is a recommended way to save/load the data model once it's been built & defined in DM?
I have a non-supported DBMS where a lot of manual steps are necessary.
If i save to .rds it drops the connections and produces the "external pointer is not valid" error after loading, although will work in the dm_draw() function. Is memoising the right path to take? 
Is there any way to just save/restore the model metadata then apply a new db connection?

**Comment by krlmlr** [comment]
Thanks, this is a frequent use case. I have tweaked the documentation, the rendered version should appear in a few minutes (new content just above the following section: https://dm.cynkra.com/dev/articles/howto-dm-db.html#transient-nature-of-operations). See also the PR linked above.
