### ISSUE TITLE
dm function with error :  Error in list_c(.) : could not find function "list_c"

### ISSUE THREAD

**Issue by wilcar** [cynkra/dm#1847]
Everything was working fine but now I have an error with dm function :  Error in list_c(.) : could not find function "list_c"

      schema<- dm(df1, df2)

**Comment by moodymudskipper** [comment]
This works fine for me :

``` r
dm::dm(cars, iris)
#> ── Metadata ────────────────────────────────────────────────────────────────────
#> Tables: `cars`, `iris`
#> Columns: 7
#> Primary keys: 0
#> Foreign keys: 0
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`list_c()` is a function from {purrr} and is imported by dm correctly at least in the current version.

Is it possible that you are using an older version of purrr ?

Can you : 

* report the output of `packageVersion("purrr")`
* update purrr with `install.packages("purrr")
* try to reproduce the issue

**Comment by krlmlr** [comment]
Looks like we need purrr >= 0.3.5.
