### ISSUE TITLE
sql_json_nest.PqConnection defined twice

### ISSUE THREAD

**Issue by HomoCodens** [cynkra/dm#1871]
While working on #1838  I noticed the method `sql_json_nest.PqConnection` is defined twice:
https://github.com/cynkra/dm/blob/67522d02ce09b662eba1b3f80fbd0a7fded9dce7/R/json_nest.R#L76
https://github.com/cynkra/dm/blob/67522d02ce09b662eba1b3f80fbd0a7fded9dce7/R/json_pack.R#L84

I assume the one in `json_pack.R` is redundant?

**Comment by krlmlr** [comment]
Good catch, looks like the second definition can be removed indeed.
