### ISSUE TITLE
Add comments to tables when drawing

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#1875]
Big organisations often have databases with a lot of cryptically named tables. There is a need for our client to be able to see a description of some tables in the `dm_draw()` output. I would imagine that setting comments would be similar to setting colors. Is that technically possible with DiagrammeR?

**Comment by TSchiefer** [comment]
What do you think of this way of describing tables? Font size, color etc. can be changed for the comment/description independently
![Description_for_dm_tables](https://user-images.githubusercontent.com/11596155/234201095-a7eb00f5-f492-4b66-9a26-e36b77062d44.png)

**Comment by TSchiefer** [comment]
the box will adapt to the width of the widest element in the box, including the comment.
It is possible to add line breaks.
I agree, for the user it would be nicer if the comments could be added like the colors. I am just not sure that this use-case is so frequent that it warrants a change of the structure of def. TBD
