### ISSUE TITLE
Frutiger font no longer shown on documentation page

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#1899]
After https://github.com/cynkra/dm/pull/1872?

See https://dm.cynkra.com/.

@wael-sadek: Can you please take a look?

CC @maelle.

**Comment by wael-sadek** [comment]
> After #1872?
> 
> See https://dm.cynkra.com/.
> 
> @wael-sadek: Can you please take a look?
> 
> CC @maelle.

#1872 Shouldn't affect it. The problem is that the source bucket `cynkraweb.s3.eu-central-1.amazonaws.com` was removed.

**Comment by krlmlr** [comment]
Works for me now.
