### ISSUE TITLE
Is the description of compute.dm() accurate ?

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#2059]
`?materialize` says :

> compute() materializes all tables in a dm to new (temporary or permanent) tables on the database.

As far as I can tell temporary tables are the unique option.

Should the description be updated ? Or should we implement the actual permanent table creation feature (if so an `overwrite` flag would be useful) ?

To build a dm with proper constraints our client needs to do some non trivial operations on raw tables, so the lazy tables that make our clean dm imply some joins or even pivots, this makes it impractical to work with lazy data, a solution to materialise those periodically on the db would be comfortable.

**Comment by moodymudskipper** [comment]
As @TSchiefer pointed to me, `compute.dm` maps to `dbplyr:::compute.tbl_sql` where we have a `temporary = FALSE` arg so we can already do this to some extent through the dots. However it will create permanent tables called "dbplyr_01" etc which defies the purpose of having something permanent.

I would suggest that when choosing permanent we create a table with the actual name of the table in the dm.

Fancier would be :

* To define the names with a glue specification, the tidyverse has uses `"{.col}"` in several places, we could use `"{.table}"`, we can also provide a named vector.
* To be able to provide a schema (fully flexible would be to be able to provide schemas table by table but maybe overkill ?).

There is a parallel between db table materialisation and memoization, I wonder if we can make materialisation more like memoization in the sense of invalidating/refreshing the "cached" (materialised) data on demand, but maybe that's out of scope and for another feature.

**Comment by krlmlr** [comment]
Thanks. Do we need to do more in the PR to clarify the issue?

**Comment by krlmlr** [comment]
`compute(temporary = FALSE)` just doesn't work as expected, at least not with current versions:

``` r
options(conflicts.policy = list(warn = FALSE))
library(dm)

con <- DBI::dbConnect(duckdb::duckdb())

dm <- dm(a = data.frame(x = 1), b = data.frame(y = 1))

dm_db <- copy_dm_to(con, dm)

dm_db_2 <- dm_db |> compute(temporary = FALSE)
#> Warning: There was 1 warning in `mutate()`.
#> ℹ In argument: `data = map(data, compute, ...)`.
#> Caused by warning:
#> ! The `name` argument of `compute()` must be provided when `temporary = FALSE`
#>   as of dbplyr 2.3.3.
#> ℹ The deprecated feature was likely used in the purrr package.
#>   Please report the issue at <https://github.com/tidyverse/purrr/issues>.

dm_db_2$a
#> # Source:   table<dbplyr_001> [1 x 1]
#> # Database: DuckDB v0.9.1 [kirill@Darwin 23.1.0:R 4.3.1/:memory:]
#>       x
#>   <dbl>
#> 1     1

DBI::dbDisconnect(con)
```

<sup>Created on 2023-11-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
