### ISSUE TITLE
Error when using copy_dm_to() on a table containing a string field with more than 255 characters

### ISSUE THREAD

**Issue by tsilber21** [cynkra/dm#2066]
I was running into errors when trying to use `copy_dm_to()` on a dm containing a table with a string field that could exceed 255 characters. Note that I am copying the dm to an MSSQL database.

The error was a SQL error reading: _String or binary data would be truncated._

After some digging, I believe the issue stems from the line in `build_copy_queries()`, which reads: `tbl <- tbl_impl(ptype_dm, x)`

It seems that it's trying to use the table with 0 rows to inform the column definitions, but this will assume VARCHAR(255) for any strings, even if that column contains a value of greater than 255 characters.

When I updated the line on my end to instead point at `dm` instead of `ptype_dm` to read `tbl <- collect(tbl_impl(dm, x))` this seemed to fix the issue.

**Comment by krlmlr** [comment]
Thanks. Is this new in dm 1.0.7? Does dm 1.0.6 work?

Alternatively, can you try #2022?

CC @TSchiefer.

**Comment by krlmlr** [comment]
You could also try #2082. I might send that to CRAN before #2022.

**Comment by tsilber21** [comment]
Should've mentioned earlier that my `dm` _is remote_, `is_src_db()` returns `TRUE`. I'm copying from one remote source to another.

1.0.6 still has this issue, but if I rollback to version 1.0.5 then the copy is fine.

Neither #2022 nor #2082 solves the issue for this dm (same truncation error).

**Comment by krlmlr** [comment]
Oh, I see. I'll work on a fix in #2022 and #2082.
