### ISSUE TITLE
Find better name for apply_filters operation

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#224]
Maybe we even need to refine the semantics?

This operation currently answers the question: what rows remain if we require that all relationships are of the form 1:n? With the exception that, if no filters are set, the dm is unchanged.

This isn't even necessary for dynafilter: we only need `dm_apply_filters_to_tbl()` for the table to be filtered, and then for the target (spatial) table. Maybe we can get rid of `dm_apply_filters()` ?

**Comment by TSchiefer** [comment]
1. We could drop `dm_apply_filters()`, but then we have the problem that filter conditions can never be "forgotten". If we do this, then I would say we should export `dm_reset_all_filters()`, so users can choose when to remove the filter conditions from the `dm`.

2. Brainstorming a possible name for "filtering" (old semantics) one table (formerly `dm_apply_filters_to_tbl()`):
- `dm_enforce_surjectivity_to_tbl()` (quite a mouthful; also the surjective relationship is from all other (filtered) tables to the given table, so it's maybe not very intuitive)
- `dm_rm_unreferred_vals_to_tbl()` (not much better)
- `dm_rm_unreferred_to_tbl()`
- `dm_keep_referred_vals_to_tbl()`
- `dm_keep_related_to_tbl()`
not sure those are particularly great, but maybe they are a place to start from...

**Comment by krlmlr** [comment]
- `dm_purge()`, `dm_crop()`, `dm_lop()`, see https://dict.leo.org/englisch-deutsch/stutzen
- `dm_relate()`

?

**Comment by TSchiefer** [comment]
- maybe `dm_prune()`?

**Comment by krlmlr** [comment]
Yeah, `dm_prune()` sounds good. It's not used much in the tidyverse yet.

I'd argue that for dynafilter we need to start with a data model that only contains rows that are somehow related to the spatial table. This means that pruning may work the same way, regardless of filter conditions.

Perhaps we can split the operation:

1. Create a logical flag (or a set of primary keys) for one or for every table that defines if a row is kept; materialized or as lazy table.
2. Pruning then means filtering by that logical flag.

**Comment by TSchiefer** [comment]
Sounds good, but maybe I'm missing something, because doesn't it also mean, that whenever one of the tables of the `dm` is changed, we need to "re-flag" all the other tables, cause the references could have been altered? It almost seems easier to:
- continue with semi-joins as before
- ignore filter conditions (treat all tables as if they had been filtered)
- try to minimize the amount of necessary semi-joins
- not bother anymore to store the filter conditions in the `dm`(?)

**Comment by krlmlr** [comment]
https://github.com/krlmlr/dm/pull/210/files#diff-ed8a30d8ca19941cf4bba4ee8136cc5dR30 is way too complicated, we really need to simplify.

**Comment by krlmlr** [comment]
Pruning is much better defined if we assume referential integrity and cardinality is 1-n everywhere. We should use this as pre-conditions and take it from there. This makes the defined filters irrelevant for pruning.

**Comment by krlmlr** [comment]
Let's wait for #237.

**Comment by krlmlr** [comment]
Thinking about the problem again, I no longer see how knowing the cardinality helps with the filtering. It may help with pruning, let's discuss that elsewhere (#347).

I still think that "apply filters" operation might be useful in conjunction with a (partial) `compute()` or with a `collect()`. I'm worried mostly about the performance of this operation with lazy tables -- currently we're repeating the same work all over in some situations. Materializing intermediate results might help, it feels we're missing some infrastructure that would help simplify this problem.

**Comment by krlmlr** [comment]
Let's deprecate `dm_apply_filters()` first (#426), and find a better name with better semantics later.

**Comment by krlmlr** [comment]
Deprecated in 1.0.0, we can filter by multiple tables in `dm_filter()` .
