### ISSUE TITLE
re-implement 'dm_learn_from_db()'

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#229]
It is the only function using `legacy_new_dm()` (with a `data_model` object as 2nd arg).

- Works without #342:
    - [ ] Define generic `dm_meta()` that dispatches on the dplyr source
    - [ ] Implement `dm_meta()` for SQLite
    - [ ] Implement `dm_meta()` for other databases

- Requires #342:
    - [ ] Implement `dm_meta()` for databases that have `INFORMATION_SCHEMA`
        - Learning from the database should be employing dbplyr/dm operations on that simpler dm instead of hard-coded SQL
    - [ ] Use `dm_meta()` in `dm_from_src()`

**Comment by krlmlr** [comment]
Calling `tbl()` is slow, we can avoid the slowness by calling `tbl_sql(vars = ...)` directly.

**Comment by krlmlr** [comment]
Now in #342.
