### ISSUE TITLE
Prefer dplyr::nest_by() over tidyr::nest()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#333]
for its stronger guarantees and better interface.

Requires dplyr 1.0.0?

Makes `nest_compat()` obsolete.

**Comment by IndrajeetPatil** [comment]
> Makes `nest_compat()` obsolete.

I don't see this function anymore, so I am assuming it's already obsolete 😅

As for `dplyr::nest_by()` over `tidyr::nest()`, the only thing to keep in mind is that the former doesn't have `.names_sep` parameter, which we seem to using:

https://github.com/cynkra/dm/blob/c89909e88a07a7d545b75fa7d94393ebf6eff713/R/json_nest.R#L32

**Comment by krlmlr** [comment]
Thanks, good catch.
