### ISSUE TITLE
Understand limitations of current implementation

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#343]
when compound keys exist in the data model.

On top of #335, or as part of it.

- [x] Implement `compound = FALSE` argument to `dm_nycflights13()`.
- [x] Walk through all functions in https://krlmlr.github.io/dm/dev/reference/. For each function:
    - find an example that uses `dm_nycflights13(compound = TRUE)`
    - add a `verify_output()` test to the bottom of the relevant `tests/testthat/test-*.R` file
        - naked, do not wrap into `test_that("...", {})`
    - do not attempt to fix

**Comment by krlmlr** [comment]
Perhaps we need more data models with compound keys in addition.

**Comment by TSchiefer** [comment]
Currently a limitation is, that `dm_nycflights13(compound = TRUE)` does not work on PG.
Error is: 
```r
Error: Failed to fetch row: ERROR:  column "(origin, time_hour)" does not exist
```

Should I ignore this for now or investigate/try solving?

**Comment by TSchiefer** [comment]
Reason is, that `build_copy_data()` interprets the key columns `(origin, time_hour)` as one column and tries to establish unique indices for it.

Should the `keys`-class maybe be a list that allows entries with length > 1?

**Comment by krlmlr** [comment]
Let's not attempt to fix for now.

**Comment by krlmlr** [comment]
When we see the big picture, it becomes clearer where to focus efforts first.

**Comment by krlmlr** [comment]
Done in #436. Need to create issues for next steps.
