### ISSUE TITLE
dm_learn_from_db and MySQL

### ISSUE THREAD

**Issue by ericemc3** [cynkra/dm#366]
looking forward to playing with this within MySQL...

**Comment by krlmlr** [comment]
I wonder if `postgres_learn_query()` works well enough for MariaDB? I never tried, would review a pull request.

**Comment by ericemc3** [comment]
It won't probably work as if, because you won't find in MySQL the same exact column names.
We are (in my company) implementing the same db model with various databases (such as MySQL, Postgres or MsSQL).

Useful requests for MySQL would be something like:
```sql
/*foreign keys*/    
SELECT column_name, constraint_name, referenced_table_name, referenced_column_name, table_name, ordinal_position
		FROM information_schema.key_column_usage
		WHERE referenced_table_name IS NOT NULL
		and table_schema = 'myschema'
		order by table_name,ordinal_position
			
/*primary keys*/  			
SELECT column_name, constraint_name, referenced_table_name, referenced_column_name, table_name, ordinal_position
		FROM information_schema.key_column_usage 
		WHERE table_schema = 'myschema'
		AND constraint_name = 'primary'
		
/*column info*/  			
SELECT * FROM information_schema.columns WHERE table_schema = 'myschema'
```

**Comment by noamross** [comment]
Would you take a PR for this or is it dependent on your expected changes in #342 and #229?

**Comment by krlmlr** [comment]
Thanks. Let me take another stab getting the internal structure right, happy to take PRs after that.

**Comment by krlmlr** [comment]
@noamross: Now that we have an idea what `dm_meta()` should look like, we could take another stab.

I've found that, across databases, `constraint_column_usage` is the most inconsistent. It seems that `REFERENTIAL_CONSTRAINTS` is the thing to use in MySQL/MariaDB?

Another thing that gave me headaches for Postgres are compound keys -- `constraint_column_usage` seems to lack a crucial column that helps infer compound keys correctly, I worked around with a custom query against the native views.

**Comment by krlmlr** [comment]
We're very close to an implementation. Do you have a chance to test it in the next few days?

**Comment by noamross** [comment]
So currently learning constraints is failing for me on a Dolt Database.  Dolt has the same information schema as MariaDB/MySQL.  But while `DoltConnection` inherits from `MariaDBConnection`, `src_DoltConnection` does not inherit from `src_MariaDBConnection`.  This is because `dbplyr::src_dbi` creates `src_` classes with `subclass <- paste0("src_", class(con)[[1]])`, ignoring other inheritance. When I debug this and modify the class so `is_mariadb()` at https://github.com/cynkra/dm/pull/1123/files#diff-44b9c1498a56325c16fa5943d640390ae701cf33675e3c88c0b079708b763a5aR70 results in TRUE, foreign and primary keys are learned correctly.

**Comment by noamross** [comment]
A hack including `src_DoltConnection`, and `src_DoltLocalConnection` would work.

**Comment by noamross** [comment]
Also, for Dolt (but also possibly MySQL/RMariaDB?), the data model returned includes all the tables and columns in _information_schema_, as well. Perhaps we want to filter out `table_schema == "information_schema"` by default?

**Comment by krlmlr** [comment]
Dolt hack added in 337de7a326e6c46061c19d48fb0181d8070072d1.

Should we add Dolt to our CI/CD (and perhaps also to RMariaDB's)?

**Comment by noamross** [comment]
That would be great. Note that you're as likely to find bugs in Dolt as it's still pretty beta. (But the Dolt team responds fast, e.g. https://github.com/ecohealthalliance/doltr/issues/46#issuecomment-1151581997).
