### ISSUE TITLE
filter.zoomed_dm() of a parent table

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#437]
Filtering a zoomed parent table will never destroy the existing unique key condition, but it could potentially destroy an existing foreign key condition, cause not all of the lookup values might survive the filtering transformation.

Maybe we could do one of the following:
1. If we wanted to cut existing foreign key relations in case a zoomed parent table is updated or inserted, we could add - in addition to the key tracking - a boolean tag, which tells us if FKs should be cut or not.
1. We could also think of stopping to track PK column(s) in case `filter.zoomed_dm()` is used.
1. In the least I think we should issue a similar warning as in `slice.zoomed_dm()`, i.e. in our case maybe:
```r
 "Keeping PK column, but `filter.zoomed_dm()` can potentially damage an existing foreign key condition due to reduced PK values."
```

**Comment by krlmlr** [comment]
These days I feel that data transformations should leave the key structure alone. There are so many edge cases, data integrity is easy to verify with `dm_examine_constraints()` .

Maybe we could speed up the latter, to examine only the tables that have been touched (compared to a base dm object)?

**Comment by TSchiefer** [comment]
Not sure I agree, since we already implemented the key tracking for most dplyr-methods for a `zoomed_dm`, and this tracking is super-fast. This issue would hopefully only lead to a better treatment of one more edge/use case.

This is not saying, that I don't find this idea interesting:
> Maybe we could speed up the latter, to examine only the tables that have been touched (compared to a base dm object)?

Would we need to ensure, that the base dm object fulfills integrity reqs? 
or maybe we could store the integrity status of the base object and continue from there?

**Comment by krlmlr** [comment]
Key tracking is different from removing keys because we updated the data. I think we should only remove keys if the column no longer exists.

Let's discuss improved integrity checks in a new issue.

**Comment by TSchiefer** [comment]
Alright, we can do that, but I think it would be good to always issue a warning in these cases, as we already do for `slice()`.

Other candidates would be `mutate()` and `filter()`
