### ISSUE TITLE
It doesn't detect tables if they are not in public schema of Postgres

### ISSUE THREAD

**Issue by vikram-rawat** [cynkra/dm#445]
I have a database where there is no public schema but multiple different schemas ( which is how a proper database is supposed to be). The moment I try dm_from_src it doesn't provide me any table whatsoever and I have no way of telling it that search in all schemas.

```
dm_from_src(learn_keys = TRUE,
            src = con,
            table_names = c("dimensions.exchange")) 

### Error: Failed to learn keys from database. Use `learn_keys = FALSE` to work around.
```

I have multiple schemas in a DB and I really want to use your package. I couldn't find anything to make it work on say dimensions schema.

**Comment by krlmlr** [comment]
Thanks. Have you tried the `schema` argument to `dm_from_src()` ?

**Comment by vikram-rawat** [comment]
Yes, I have. first of all, I had to dig that argument up by reading the code. It should be documented

It turns out to be you can only give one schema at a time. If you could please make it a little flexible to work on more than one schema. like if 2 tables have the same name but are in different schemas.

This is a great package and I would love to use it more and more because I work with Databases all the time. Please come up with a solution.

**Comment by vikram-rawat** [comment]
I had same problem with datamodeler. I was able to extract data from different schema but then I have to manually change the name of every column. because my schema had 2 table by same name and it graphed it as single table everytime. I have raised an issue there too....

https://github.com/bergant/datamodelr/issues/23

**Comment by krlmlr** [comment]
AFAICT it's documented, a bit hard to find. I'm happy to review a pull request that improves the documentation.

Have you seen `dm_bind()` ?

**Comment by vikram-rawat** [comment]
Thanks for replying. I Just tried but it's like if you have same names across schemas then it causes a problem.
```
Error: Each new table needs to have a unique name. Duplicate new name(s): `prices`, `balance_sheet`...
```

**Comment by krlmlr** [comment]
Yeah, you'll need to make the tables unique before binding. Do you think `dm_bind()` should have a name repair argument?

**Comment by krlmlr** [comment]
This *might* work better with the current development version. Could you please take a look?

**Comment by krlmlr** [comment]
Please open new issues, referencing this issue, if problems persist.
