### ISSUE TITLE
Integrate with nomnoml?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#466]
https://github.com/rstudio/nomnoml

**Comment by krlmlr** [comment]
- Keys
- Direction of relationship
- Cardinality
- Labeled relationships (#402)

**Comment by moodymudskipper** [comment]
Here is an example of what we can do with nomnoml : tinyurl.com/246hw4ym

![image](https://user-images.githubusercontent.com/18351714/119570570-98c6ef00-bdb0-11eb-89d0-ec5ba8d1e5e0.png)

It will be less flexible than the current solution in many respects, and probably less pretty. For instance we can't link nested items to a block on the outside, and we can only use one format (color, font...) by block.

Should we proceed or are these limitations not acceptable ?

**Comment by krlmlr** [comment]
Oh, I wasn't aware of these limitations. Let's shelve for now.

**Comment by krlmlr** [comment]
Maybe it's useful for another type of diagram.

**Comment by krlmlr** [comment]
Let's discuss in #93.
