### ISSUE TITLE
saving and loading dm from working directory

### ISSUE THREAD

**Issue by calleja** [cynkra/dm#483]
Is there a method or step sequence to save a dm from a db source and later load it while retaining connections? The dm will load fine from an .RData file, however, it can't be manipulated after loading, citing error "Invalid connection". 

Perhaps converting the source of a dm from db to dataframe could work here, but there is no function for that (would be optimal to doing this manually so that all table relations are preserved).

Additionally, I tried loading the WD, then re-establishing the dbi connection, but that doesn't resolve,

save.image('S:/FMA/Luis/cdw/cdwPipeline_02_22_21.Rdata')
#restore entire working directory
load('S:/FMA/Luis/cdw/cdwPipeline_02_22_21.Rdata')
pull_tbl(dm_cdw_pre_2020.0,cdw_transaction_cln3) -> produces the 'Invalid connection' error

**Comment by krlmlr** [comment]
Thanks. In our projects, we tend to create functions that connect to the database (if necessary) and then return a working dm object. This avoids the need for serialization.

You could also use `dm_paste()` to create code that establishes the keys.

**Comment by krlmlr** [comment]
Does this work for you? Would you like to contribute a documentation update?

**Comment by moodymudskipper** [comment]
> Perhaps converting the source of a dm from db to dataframe could work here

The use case seems to be with small data here. @krlmlr I don't think we have a simple way to fetch all tables to create a dm containing only local data frames do we ? It seems to me it would solve this use case and might be useful in general ? It might come with warnings and safe defaults not to try to fetch a huge db.

We have an [upload section in the reference](https://krlmlr.github.io/dm/reference/index.html), we might have some download utilities too ?

**Comment by maskegger** [comment]
Hi @krlmlr , trying to use dm in a project with a [targets](https://github.com/ropensci/targets/) pipeline - would you suggest that not save any intermediate dm objects and is there a best practice in case we want to save them to disk? Thanks for all the work!

**Comment by krlmlr** [comment]
This is different, depending on if you have a local dm with data frames, or a dm pointing to a database:

- local dm: save and restore with `saveRDS()` and `readRDS()`
- remote dm: create a function that takes a DBI connection object as argument and returns a dm object. Can't save those to disk, yet

What am I missing?
