### ISSUE TITLE
Error in how-to-dm-copy vignette

### ISSUE THREAD

**Issue by rorynolan** [cynkra/dm#535]
<img width="857" alt="Screen Shot 2021-05-03 at 11 53 00 AM" src="https://user-images.githubusercontent.com/20400852/116919503-3726c100-ac06-11eb-8e58-e306d9df015e.png">

Pretty sure this should read "The table name, dbplyr_001, was automatically generated as the name argument was not supplied.

I think you should also clarify where the name argument was omitted. In `sql_render()`?

Thank you for the package. It's working great for me right now as I try to work through how to set up a MySQL db.

**Comment by krlmlr** [comment]
Thanks. I believe this problem originates in https://github.com/tidyverse/dbplyr/issues/639 and should be fixed by https://github.com/tidyverse/dbplyr/pull/649. Working around.
