### ISSUE TITLE
dm_rows_delete() to use all columns if no pk is set

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#575]
So we can remove rows conveniently from fact tables

**Comment by krlmlr** [comment]
I think this is reasonable. Should the same apply to `dm_rows_insert()`? It's likely an error for update or upsert.

**Comment by krlmlr** [comment]
I'm no longer sure, because on the database `NULL` never matches. I think it's reasonable to require primary keys for `fk_repair = "delete"` .
