### ISSUE TITLE
Support passage of `pool` object to `dm_from_src`

### ISSUE THREAD

**Issue by brancengregory** [cynkra/dm#599]

**Comment by krlmlr** [comment]
Thanks. If it doesn't work currently, could you please provide a reprex, perhaps with the RSQLite or duckdb packages?

**Comment by jaredlander** [comment]
This isn't exactly the reprex you asked for, but it's what I have on hand.

```r
conn <- pool::dbPool(
    odbc::odbc(),
    Driver = "postgresql",
    Server = 'server_address',
    Port = 'port',
    Database = 'database_name',
    UID = 'user',
    PWD = 'password',
    timeout = 10
)

thedb_raw <- dm_from_src(conn, learn_keys=FALSE)

> Error in UseMethod("sql_escape_ident") : 
  no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

**Comment by krlmlr** [comment]
Thanks. AFAICT you need to "check out" a connection from a pool object to be able to work with it. Are you suggesting to enhance dm so that it will auto-checkout as needed?

**Comment by jaredlander** [comment]
Well that's something I didn't know about.

This works.

```r
thedb_raw <- dm_from_src(conn %>% pool::poolCheckout(), learn_keys=FALSE)
```

But for an end user, having `{dm}` check it out might make a lot of sense. Especially if it is used in `{shiny}`, I'm not quite sure where/when it should be checked out and returned.

**Comment by krlmlr** [comment]
Thanks, makes sense. We might be able to check out and return during initialization of the dm object, so that each table access does its own checkout if needed.

**Comment by jaredlander** [comment]
If you return at creation, do you need to checkout again each time you perform work on the object?
 And will mutations be written to the database?

**Comment by krlmlr** [comment]
To support Pool objects in dm we'd need to make them work transparently in dbplyr first.

dm objects are immutable, except for the `dm_rows_*()` family of functions. What mutations are you referring to?

**Comment by jaredlander** [comment]
I'm not at the computer, but if we wanted to do something like `dm_insert_zoomed()` after we return the pool connection, would that work?

**Comment by krlmlr** [comment]
`dm_insert_zoomed()` only modifies the metadata stored on the client-side, it never executed DDL on the server.

**Comment by jaredlander** [comment]
I thought there was a way to write back to the database (still learning the package, this is my first time using it extensively)

**Comment by krlmlr** [comment]
Yes, we can also create the database structure via `copy_dm_to()` . All these operations are explicit -- if there are interactions with {pool}, dm needs to be made aware of those.

**Comment by moodymudskipper** [comment]
Here's a SQLite repress : 

```
conn <- pool::dbPool(RSQLite::SQLite(), "", timeout = 10)
DBI::dbWriteTable(conn, "mtcars", mtcars) # necessary to reproduce issue
thedb_raw <- dm::dm_from_src(conn, learn_keys = FALSE)
#> Error in UseMethod("sql_escape_ident"): no applicable method for 'sql_escape_ident' applied to an object of class "c('Pool', 'R6')"
```

**Comment by moodymudskipper** [comment]
`pool:::db_write_table.Pool` simply calls `db_con <- poolCheckout(con)` then `on.exit(poolReturn(db_con))`


```
pool:::db_write_table.Pool
function (con, table, types, values, temporary = FALSE, ...) 
{
    stopIfTemporary(temporary)
    db_con <- poolCheckout(con)
    on.exit(poolReturn(db_con))
    dplyr::check_dbplyr()
    dplyr::db_write_table(db_con, table = table, types = types, 
        values = values, temporary = temporary, ...)
}
```

Do we just just need in `dm_from_src`  :

```
if (inherits(src, "") {
    src <- pool::poolCheckout(src)
    on.exit(pool::poolReturn(src))
} 
```

+ suggest pool package and check if installed ?

**Comment by krlmlr** [comment]
Yeah, it's worth a try.

**Comment by krlmlr** [comment]
Turns out we need to add more methods.

**Comment by krlmlr** [comment]
Closing as stalled. Please open a new issue with reference to this issue if this is still a problem.
