### ISSUE TITLE
Integrate with pixarfilms package?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#600]
One parent table, multiple children. Implicit m:n relations.

CC @erictleung.

**Comment by erictleung** [comment]
Oh, very cool, I'll have to take a look at this. This does seem a natural use case for pixarfilms. I'm also really liking the visuals that can be made with dm! Let me know how I can help.

**Comment by krlmlr** [comment]
Would you like to implement a function that creates a dm object for the data provided by your package?

**Comment by erictleung** [comment]
@krlmlr sure thing! The issue title is still a bit unclear to me. Were you thinking of having the function written within the {dm} package to generate a dm object? Kind of like what was done with the nycflights13 data? https://github.com/cynkra/dm/blob/main/R/nycflights13.R

**Comment by krlmlr** [comment]
That, or pixarfilms exports a function like this. I'm fine either way.
