### ISSUE TITLE
multiple keys with same foreign key

### ISSUE THREAD

**Issue by luispfonseca** [cynkra/dm#606]
Thanks for this great package.

I am working with a dataset where I have links between entities (they are in pairs, let's say) and I have outside information about each id of those entities in a common table. When I try to join/flatten, `dm` identifies a cycle, even though I think technically there isn't one (also `dm_draw` does not show it). 

I think the issue is that there will be duplicated columns. I couldn't really find a solution to this issue of mine in the documentation. I think this reprex shows more clearly what I want to do and what I get.

``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

pairs <- tibble(id1 = c(1, 2, 3), id2 = c(2, 4, 5))
names <- tibble(id = 1:5, name = letters[1:5])

pairs
#> # A tibble: 3 x 2
#>     id1   id2
#>   <dbl> <dbl>
#> 1     1     2
#> 2     2     4
#> 3     3     5
names
#> # A tibble: 5 x 2
#>      id name 
#>   <int> <chr>
#> 1     1 a    
#> 2     2 b    
#> 3     3 c    
#> 4     4 d    
#> 5     5 e

# what i'd want
pairs %>% 
  left_join(names %>% rename(id1_names = name), by = c("id1" = "id")) %>% 
  left_join(names %>% rename(id2_names = name), by = c("id2" = "id"))
#> # A tibble: 3 x 4
#>     id1   id2 id1_names id2_names
#>   <dbl> <dbl> <chr>     <chr>    
#> 1     1     2 a         b        
#> 2     2     4 b         d        
#> 3     3     5 c         e

# setting up dm
dm <- 
  dm(pairs, names) %>% 
  dm_add_pk(pairs, c(id1, id2)) %>% 
  dm_add_pk(names, id) %>% 
  dm_add_fk(pairs, id1, names, id) %>% 
  dm_add_fk(pairs, id2, names, id)

# reprex package doesn't show the drawing, but can be checked here
# i think it shows there's no cycle
dm_draw(dm) %>% print()

# error
# also, says there's a cycle but doesn't show it
dm %>% 
  dm_flatten_to_tbl(pairs, names)
#> Error: Cycles in the relationship graph not yet supported.
#> * Shortest cycle:

dm %>% 
  dm_join_to_tbl(pairs, names)
#> Error: Cycles in the relationship graph not yet supported.
#> * Shortest cycle:
```

**Comment by krlmlr** [comment]
Thanks. The parallel edges between `pairs` and `names` count as an undirected cycle in this case.

An easy way forward is the implementation of an operation that cracks all circles by duplicating all relevant tables. To do this manually, duplicate the `names` table in the dm object and ensure that each of the two `names` table has only one relationship.

**Comment by luispfonseca** [comment]
Thank you. Is there anyway to ensure consistency between the two duplicate tables? And if I understand correctly, this is something you'd eventually implement in the background, correct?

Thank you once again for the great package.

**Comment by krlmlr** [comment]
If the tables are read-only data frames, the data will stay consistent. If they are tables on the database, the sequence `. %>% dm_zoom_to(...) %>% dm_insert_zoomed("...")` will create a "local view" -- the two dm tables will point to the same table on the database. Does this make sense?
