### ISSUE TITLE
`rows_update()`: Conditional Update & Mutating Join

### ISSUE THREAD

**Issue by mgirlich** [cynkra/dm#609]
In my opinion `dplyr` is, unfortunately, quite weak compared to SQL when it comes to joins and in particular mutating joins. For `rows_update()` and `rows_upsert()` I like the following two things that are possible with SQL.

## Conditional Update
Currently, `rows_update()` just checks if the columns specified in `by` match and then updates. There are situations where it would be useful to have other (SQL) conditions, e.g. only update if `created_at >= now() - interval '2 hours'`. This is a bit related to the work on flexible joins in dplyr https://github.com/tidyverse/dplyr/pull/5910 and also to your issue on conditional mutates https://github.com/tidyverse/dplyr/issues/4050

## Mutating join
Instead of only overwriting the value of the columns in `x` it would be useful if one could apply custom SQL to it, e.g. `retry_counter = retry_counter + 1` or to concatenate to a json column `details = details || {"updated": true}`.
A special case of this is `rows_patch()` where we basically have `x = coalesce(x, new.x)`.

## Example
```r
sql_rows_update(
  x = tbl(con, "test"),
  y = data.frame(
    id = 1:3,
    value = "z",
    updated_at = Sys.time()
  ),
  copy = TRUE,
  update = list(
    "value",
    retry_counter = sql("retry_counter + 1"),
    "updated_at"
  ),
  by = list(
    "id",
    sql("created_at >= now() - interval '2 hours'")
  )
)
```

Basically, the `update` argument could be similar to `mutate()` and also translate R code

```r
update = update_with(
  value, # update `x$value` with `y$value`
  value2 = coalesce(x$value2, y$value2),
  retry_counter = x$retry_counter + 1,
  updated_at = sql("now()")
)
```

## Mutating Join via `f_update()`
While working on `rows_patch()` I thought another strategy might be to add an argument `f_update()`: a named list of functions. These functions have two arguments `x` and `y` that and output the wanted query. For example to update the column `col_update` and patch the column `col_patch` you could pass

```r
f_update <- list(
  col_update = function(x, y) y,
  col_patch = function(x, y) paste0("COALESCE(", x, ", ", y, ")")
)
```

If nothing is specified it would simply update and by providing a function instead of a list it would apply this function to all columns.
My example above with the `retry_counter` could work even without a column `retry_counter` in the table `y`.
It would not be possible to combine different columns but I don't see much of a use case for this anyway.

**Comment by krlmlr** [comment]
Should we wait on the upstream pull request before taking action here? I suspect most of this should live in dbplyr.

**Comment by mgirlich** [comment]
Yes, I am happy to wait for the PR. Mentioning `dbplyr`: when should the `rows_*.tbl_dbi()` functions be transferred to `dbplyr` ? At least I guess that's where they should end up, right?

**Comment by mgirlich** [comment]
Closing as `rows_*()` is now implemented in dbplyr.
