### ISSUE TITLE
Support `returning` for `in_place = FALSE`

### ISSUE THREAD

**Issue by mgirlich** [cynkra/dm#611]
It's basically possible with one restriction for insert operations (`rows_insert()` and `rows_upsert()`): only columns in `y` can be returned. This is relevant for columns in `x` that have default values or are a sequence (the typical `id` column).
But if one is interested in the `id` column than `in_place = FALSE` doesn't make much sense any way so this should be fine if it is documented.
@krlmlr what do you think about the restrictions?

**Comment by krlmlr** [comment]
It seems that the PR returns all columns from `rows_insert()`; I don't mind if the columns missing from `y` are filled with `NA`; users who want to simulate an ID column will need to do it themselves (or have a dedicated vctrs subclass take care of it).

**Comment by mgirlich** [comment]
In all other functions it kind of happened automatically that all columns of `x` were resp. could be returned. For consistency I did the same thing for `rows_insert()`.
