### ISSUE TITLE
Document new `returning` argument to `rows_*()`

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#612]
in vignette.

CC @mgirlich.

**Comment by krlmlr** [comment]
I wonder if we should switch to standard evaluation for the `returning` argument, given that we can't seem to fix the warning (upstream: https://github.com/r-lib/rlang/issues/1251).

**Comment by mgirlich** [comment]
The nice thing about tidyselect is that one can return every column. This is quite useful when you want to get an ID column from the database. An alternative would then be to support passing SQL to `returning`. Then one could simply write `returning = sql("*")` (though one might need to specify the table, i.e. `returning = sql("target.*")`).

**Comment by krlmlr** [comment]
We could ask the user to quote, as an exception.

**Comment by krlmlr** [comment]
`returning = quote(everything())`

**Comment by krlmlr** [comment]
dbplyr business now.
