### ISSUE TITLE
`rows_*()`: add `na_matches` argument

### ISSUE THREAD

**Issue by mgirlich** [cynkra/dm#619]
It probably makes sense to allow the user to control whether two `NULL`s should be considered equal or not. Maybe this should be possible on a per column basis, i.e. `na_matches` could either be a scalar or a named character vector.

**Comment by krlmlr** [comment]
Is it supported by dplyr?

**Comment by mgirlich** [comment]
It is supported by `dbplyr` but only as a scalar.

**Comment by mgirlich** [comment]
Closing as `rows_*()` is now implemented in dbplyr.
