### ISSUE TITLE
Stronger support for unique keys

### ISSUE THREAD

**Issue by TSchiefer** [cynkra/dm#622]
With #561 (closing #402) already some support for the concept of multiple primary keys was introduced.
After this PR FKs to a table can refer to different columns. But there will always be just 1 "official" PK at a time. My suggestion is to make it possible to have several PKs at a time which have "equal rights".

Things that would need to be adapted:
1. `dm_add_pk()` (`dm_rm_pk()` may already be ok)
1. `dm_add_fk()`
1. Drawing a dm
1. print dm to console (`print.dm()`, `glimpse.dm()` (after #605))
1. potentially setting key relations when copying a dm to a DB (might already work though for the supported DBMS)

**Comment by krlmlr** [comment]
We now have implicit support for linking to columns other than PK columns. Some (most?) databases enforce this constraint. We might want to copy this:

- Each FK linking to non-PK creates an (implicit) unique key
- We can also create unique keys explicitly
- `dm_examine_constraints()` checks uniqueness here too

**Comment by krlmlr** [comment]
I still think each table should have at most one primary key, and an arbitrary number of unique keys.

**Comment by krlmlr** [comment]
This can also help implement #1386 in a robust way.

@nbenn and @TSchiefer wondered if the row order returned by the `RETURNING` clause matches the insertion order. The answer is: in the best case we can assume that, but we're not sure. In the worst case, there's a reshuffling.

One solution could be to require, for each autoincrement PK, a unique key that doesn't contain the column of that autoincrement PK. This would allow unambiguously matching the database-generated values to the rows that we insert.

@TSchiefer: could you please provide infrastructure for specifying unique keys in a dm object? Can you give an ETA? Perhaps `dm_add_fk()` would automatically add a unique key if it's linking against a non-primary key, for full consistency.

**Comment by TSchiefer** [comment]
So the idea is to artificially create a compound key?
What if we instead just use all columns of the inserted rows with rows_append to match the rows of in y for the AI-PK-table?
If there are duplicate entries (i.e. all values apart from the AI PK) we can just match those by order (just need to make sure we deduplicate)

That way we don't need new infrastructure.

**Comment by krlmlr** [comment]
Thought about that. Returning `everything()` can be unnecessarily expensive, e.g., in the presence of BLOB columns.

**Comment by nbenn** [comment]
You‘ll also end up comparing floating point numbers and if you start considering nested data types etc., this might become messy.On 23 Dec 2022, at 09:10, Kirill Müller ***@***.***> wrote:﻿
Thought about that. Returning everything() can be unnecessarily expensive, e.g., in the presence of BLOB columns.

**Comment by TSchiefer** [comment]
> Thought about that. Returning everything() can be unnecessarily expensive, e.g., in the presence of BLOB columns.

Good point, and if we excluded BLOB columns we run into the original problem again...

**Comment by TSchiefer** [comment]
As for the user-facing side: Would a new function `dm_add_uk()` be alright with you?

**Comment by TSchiefer** [comment]
Also: if there is no UK defined and there is an AI PK, should we do it the way it was and issue a warning?

**Comment by TSchiefer** [comment]
ETA possibly in a week?

**Comment by nbenn** [comment]
﻿I feel that requiring uniqueness is too strong. In many legitimate cases this will not be given. One way out of this could be transiently adding a row id col in cases where we do not have uniqueness and then using that for mapping.An opt out setting for this would be nice too, as (at least in Postgres) relying on ordering might be ok (cf. https://stackoverflow.com/a/27996203).On 23 Dec 2022, at 09:17, Tobias Schieferdecker ***@***.***> wrote:﻿
Also: if there is no UK defined and there is an AI PK, should we do it the way it was and issue a warning?

**Comment by TSchiefer** [comment]
True, but the user could always proactively add the row id col themselves and specify it as a unique key.

**Comment by krlmlr** [comment]
`dm_add_uk()` sounds good. If we go that route, I'd make absence of a unique key a hard fail if required.

Happy to discuss concerns.

**Comment by krlmlr** [comment]
We can start with this feature either way, regardless of what we do for the autoincrement feature.
