### ISSUE TITLE
dm_examine_constraints fails if pk was renamed

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#693]
And it fails worse if the initial name has an accessible value (e.g. the name is `id` and {dplyr} is attached, making the `id` function available)

``` r
library(dm, warn.conflicts = FALSE)
library(tibble)

dm1 <- 
  dm(A = tibble(id =1), B = tibble(id =1)) %>% 
  dm_add_pk(A, id) %>% 
  dm_add_fk(B, id, A)

dm1 %>% 
  dm_rename(A, new_id = id) %>% 
  dm_examine_constraints()
#> Error: Problem with `mutate()` column `problem`.
#> ℹ `problem = pmap_chr(fks_tibble, ticker(check_fk))`.
#> x Problem adding computed columns in `group_by()`.
#> x Problem with `mutate()` column `value1`.
#> ℹ `value1 = id`.
#> x `value1` must be a vector, not a function.


dm2 <- 
  dm(A = tibble(id2 =1), B = tibble(id2 =1)) %>% 
  dm_add_pk(A, id2) %>% 
  dm_add_fk(B, id2, A)

dm2 %>% 
  dm_rename(A, new_id2 = id2) %>% 
  dm_examine_constraints()
#> Error: Problem with `mutate()` column `problem`.
#> ℹ `problem = pmap_chr(fks_tibble, ticker(check_fk))`.
#> x Problem adding computed columns in `group_by()`.
#> x Problem with `mutate()` column `value1`.
#> ℹ `value1 = id2`.
#> x object 'id2' not found
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

(1)
I believe we want `dm_examine_constraints` to never crash on a <dm>, and to give helpful info on a corrupted <dm> as to how to fix it. 

(2)
The "`value1` must be a vector, not a function." error would be more generally avoided if we'd use `.env` in `mutate()`. Should we make sure we use `.env` and `.data` everywhere in the package ?

**Comment by krlmlr** [comment]
- `validate_dm()` should complain
- we should use `!!` internally when we refer to variables from the environment, but this is not necessarily a problem here
- We *could* use `.data[[var]]` in this particular scenario, in general I prefer leaving it out
- we need a test

**Comment by krlmlr** [comment]
Seems to work now:

``` r
library(dm, warn.conflicts = FALSE)
library(tibble)

dm1 <-
  dm(A = tibble(id = 1), B = tibble(id = 1)) %>%
  dm_add_pk(A, id) %>%
  dm_add_fk(B, id, A)

dm1 %>%
  dm_rename(A, new_id = id) %>%
  dm_examine_constraints()
#> ℹ All constraints satisfied.

dm2 <-
  dm(A = tibble(id2 = 1), B = tibble(id2 = 1)) %>%
  dm_add_pk(A, id2) %>%
  dm_add_fk(B, id2, A)

dm2 %>%
  dm_rename(A, new_id2 = id2) %>%
  dm_examine_constraints()
#> ℹ All constraints satisfied.
```

<sup>Created on 2022-06-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
