### ISSUE TITLE
duplicated entries in Reference section of website

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/dm#695]
https://cynkra.github.io/dm/reference/index.html

![image](https://user-images.githubusercontent.com/11330453/141279440-d46508d1-e786-472b-b8e2-02119b3ccb06.png)

**Comment by krlmlr** [comment]
Thanks. I suspect this is a pkgdown buglet that will auto-resolve. Let's watch out for this.

**Comment by IndrajeetPatil** [comment]
I think this is the issue:
https://github.com/r-lib/pkgdown/issues/1916

Once it is resolved, the current issue can also be closed.

**Comment by IndrajeetPatil** [comment]
Should be fixed now.
