### ISSUE TITLE
Foreign key can reference self

### ISSUE THREAD

**Issue by joethorley** [cynkra/dm#696]
I'm wondering if ideally this behaviour should throw an error.
``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter

tbl <- data.frame(col = 1)
tbl <- dm(tbl) |>
  dm_add_fk(tbl, col, tbl, col, check = TRUE)

dm_draw(tbl)
```

![](https://i.imgur.com/0IE0uPk.png)

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
Probably. How do databases behave?

**Comment by joethorley** [comment]
Apparently its not a problem. So I'm going to close this issue.

``` r
library(DBI)
library(RSQLite)

conn <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

tbl <- data.frame(col = 1L)

DBI::dbExecute(conn, "CREATE TABLE tbl (
                col INTEGER PRIMARY KEY NOT NULL,
                FOREIGN KEY (col) REFERENCES tbl (col))")
#> [1] 0

DBI::dbAppendTable(conn, "tbl", tbl)
#> [1] 1

DBI::dbReadTable(conn, "tbl")
#>   col
#> 1   1

DBI::dbDisconnect(conn)
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by joethorley** [comment]
I've just been realizing this is useful behaviour with composite keys because it allows rows to reference other rows in the same table.
