### ISSUE TITLE
Handling missing values in foreign keys

### ISSUE THREAD

**Issue by famuvie** [cynkra/dm#706]
Hi. This is not necessarily an error, but a somewhat unexpected behaviour when there are missing values in the foreign key of a table.
I would expect that calling `fm_filter()` with a trivial filter (i.e. all rows are kept) would result in the original `dm` object. Yet, this is not what happens in this case:
``` r
## Make a test-dm
library(dm, quietly = TRUE)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
A <- data.frame(
  id = 1:3,
  type = c(100, NA, 300),
  name = paste0("A", 1:3)
)
B <- data.frame(
  id = c(100, 300),
  desc = paste0("B", 1:2)
)

tdm <- dm(A, B) %>% 
  dm_add_pk(A, id) %>% 
  dm_add_pk(B, id) %>% 
  dm_add_fk(A, type, B)

## Check
dm_get_tables(tdm)
#> $A
#>   id type name
#> 1  1  100   A1
#> 2  2   NA   A2
#> 3  3  300   A3
#> 
#> $B
#>    id desc
#> 1 100   B1
#> 2 300   B2
dm_draw(tdm, view_type = 'all')
```

![](https://i.imgur.com/PTXxwG5.png)

``` r
## Filtering rows in B drops rows with NA in A's FK
dm_filter(tdm, B, desc == 'B1') %>% 
  dm_apply_filters_to_tbl('A')
#>   id type name
#> 1  1  100   A1

## This violates the expectation that keeping all the rows in B
## should preserve all the rows in A.
dm_filter(tdm, B, TRUE) %>% 
  dm_apply_filters_to_tbl('A')
#>   id type name
#> 1  1  100   A1
#> 2  3  300   A3
```

<sup>Created on 2021-11-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

On the other hand, I understand that there might be situations where this behaviour is expected. If I request all the rows in A that point to a specific row in B, I don't necessarily want additional rows with NA's in the FK.
However, this would be consistent with R's behaviour in other settings. E.g. when subsetting vectors:
``` r
A <- data.frame(
  id = 1:3,
  type = c(100, NA, 300),
  name = paste0("A", 1:3)
)
A$type[A$type == 100]
#> [1] 100  NA
```

<sup>Created on 2021-11-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
Thanks. I think this behavior is intentional. What does `dm_examine_constraints()` show for your data?

**Comment by famuvie** [comment]
After _applying filters_, all constraints are satisfied.

**Comment by famuvie** [comment]
Oh... if this is intended I'm in trouble. Do you see a workaround for applying the filter while keeping rows with `NA` in the FK in table A?

Thanks.

**Comment by krlmlr** [comment]
This fell through the cracks.

I suggest to convert the `NA` values to an explicit "missing" value, and add a dummy row to the parent table.

**Comment by famuvie** [comment]
Thanks. That would do, indeed.
