### ISSUE TITLE
pack_join

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#721]
For #595

**Comment by moodymudskipper** [comment]
Drafted in https://github.com/cynkra/dm/tree/f-721-pack_join

``` r
library(dm, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
band_members %>% pack_join(band_instruments)
#> Joining, by = "name"
#> # A tibble: 3 × 3
#>   name  band    band_instruments$plays
#>   <chr> <chr>   <chr>                 
#> 1 Mick  Stones  <NA>                  
#> 2 John  Beatles guitar                
#> 3 Paul  Beatles bass
```

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It has the same arguments as `nest_join()`.

**Comment by krlmlr** [comment]
Thanks, the code looks good. Can you please merge/rebase and open a PR when ready?
