### ISSUE TITLE
"spec" object for dm_to_tibble()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#734]
`pivot_longer()` is implemented as a combination of `tidyr::build_longer_spec()` and `tidyr::pivot_longer_spec()`, similarly for `pivot_wider()` . We could do the same for `dm_to_tibble()` .

The spec object could be a tibble internally, and print as a sequence of `dm_unwrap()` calls.

After #730.

**Comment by moodymudskipper** [comment]
A `dm` itself is a tibble and contains all the spec we need, so using the original dm as a spec makes sense to me.
However it's not necessarily easy to define manually, so I offered in current work the option to provide a list of pks and fks. 
If this needs to be a tibble and have a custom class we might make a it a single row 2 columns tibble.
Another solution is to expect the spec to have the same format as the output from `dm_get_def()` (only table pk fk columns would be required).Not super easy to generate manually but we could have a helper function to generate specs.

**Comment by krlmlr** [comment]
I like the idea. We have `dm_paste()` for showing the code to define an existing dm. The dm however contains more than necessary for a `dm_to_tibble()` spec: the payload (=non-key) columns aren't strictly necessary. Also, how to create a sequence of `dm_unwrap()` calls from a dm?

If we follow this route, would an internal function that sorts the tables in depth-first order (based on a certain root) be helpful?

**Comment by krlmlr** [comment]
Using dm objects as specs for now.
