### ISSUE TITLE
Wrapping dm objects with circular references

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#751]
Doesn't work yet after #737. I wonder if it even should.

Ultimately we want a way to wrap and unwrap `dm_nycflights13(cycle = TRUE)` and other similar constructs. One way to achieve this is to create two "views" for the `airports` table. I remember we had an issue that describes this operation, but haven't looked.

Preprex:

``` r
library(dm)

dm_nycflights13(cycle = TRUE) %>%
  dm_treeify()
```

![](https://i.imgur.com/FZ6rJYk.png)

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The inverse operation could again take a dm ptype as argument.

**Comment by TSchiefer** [comment]
> I remember we had an issue that describes this operation, but haven't looked.

Think it was this one: #55

**Comment by krlmlr** [comment]
Fixed with `dm_disentangle()` when it's exported.
