### ISSUE TITLE
Split planning and doing in dm_wrap()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#752]
Recursively traverse the relationship graph to create a recipe that is then applied in one swoop (e.g. via `purrr::reduce2()`).

This allows for earlier detection of failure and better tests.

**Comment by moodymudskipper** [comment]
Does `dm_unwrap_tbl()` need this split too between planning and doing ? That would be more complicated

**Comment by krlmlr** [comment]
Yes, if we want to support progress bars here too. Given the ptype, how is the creation of the recipe different from `dm_wrap_tbl()` ? Can we use the same recipe reversed?
