### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#757]
Guidelines to collaborate on {dm}

I suppose a build ignored md file in the root folder is fine ? `COLLAB.md` ? unless there is a standard for that already ?

The goal is to facilitate external collaboration and onboarding, and structure our approach of development, i.e. write the unwritten rules and some more.

For example in no special order: 

* function names
* tests
* how we do to test multiple data sources
* where to declare global variables
* reference to tidyverse principles
* error helpers
* ...

It should be built incrementally and with no pretense of exhaustivity or perfect structure at first, it can live on its [own branch](https://github.com/cynkra/dm/tree/f757-collaboration-guide) until it has enough content and is structured enough, then we can merge it and still update it regularly.

I suppose when we get enough there we can isolate specific dm guidelines from general Cynkra guidelines.

I think this thread is also a good place for questions and short discussions on specific aspects.

**Comment by moodymudskipper** [comment]
Is the following rule correct ?

> All {dm} functions that are applied on `dm` objects should be prefixed by `"dm_"`, with the exception of S3 methods where the generic is defined outside of the package. Inversely, objects prefixed with `"dm_"` should be functions applied to `dm` objects, OR be `dm` objects themselves.

2 exceptions to this rule are `pull_tbl()` and `copy_dm_to()`, is there a reason other than backward compatibility why these wouldn't be names `dm_pull_tbl()` and `dm_copy_to()` ?

**Comment by moodymudskipper** [comment]
Is this correct ?

> We strive to standardise error messages in {dm}. A failure should be triggered by `abort()` through a function defined in "error-helpers.R" where the error class is defined with `dm_error_full()` and the error message is created by a separate function. Please follow the pattern used in `"error-helpers.R"`.  Exceptions might exist but they are mostly waiting to be harmonised.

**Comment by TSchiefer** [comment]
According to https://cynkra.github.io/dm/articles/tech-dm-naming.html your explanation of the function naming seems correct to me (and sounds good in addition).

I would tentatively agree about renaming `pull_tbl()` (I think we thought about it, though, and decided it's better like that because of it's similarity to `dplyr::pull()`, but one dimension higher; but according to the rule, I agree with you).
Regarding `copy_dm_to()`: since the first argument is the destination (data source or connection), it should probably not be called `dm_copy_to()`? (we actually made the switch from `dm_copy_to()` to `copy_dm_to()` a while back)

**Comment by moodymudskipper** [comment]
Thanks, I think I will just link to the vignette not to duplicate the info, I had forgotten about it.

**Comment by moodymudskipper** [comment]
Is this correct ?

## test guidelines  
  
* We use {testthat}
* All exported functions should be tested
* R scripts under "tests/testthat/"" whose name start with "helper"" are loaded 
  with `devtools::load_all()` so they are available for both tests and interactive 
  debugging, but can't be found with `dm:::helper_function()`
* "helper-src.R" implements a complex mechanism so that some dm creating functions,
  such as `dm_for_filter()`, will create a remote dm in a different database
  management system depending on context. This allows tests that use those to
  be run on different setups through github actions. Additionally `my_db_test_src()`
  will return the relevant database. In order to test databases 
  locally (typically to debug if CI tests fails and we can't debug from the online log)
  we can set the environ variable "DM_TEST_SRC" to "postgres", "mariadb", "mssql", "duckdb" or "sqlite".
  You might have to setup credentials in "helper-config-db.R" to do so.
* Some useful expectations can be found in "helper-expectations.R"
* In "helper-skip.R" are some helpers to skip tests in some contexts, these might
  be useful for instance if a feature is not supported on some databases
* When using `expect_snapshot()` on a DBMS dependent call (i.e a call that uses `dm_for_filter()`
  or copies to `my_db_test_src()`), 
  the `variant` argument should be   set to `my_test_src_name` (a global 
  variable created when loading helpers) so that the snapshots end up in different 
  directories.

**Comment by krlmlr** [comment]
Thanks, looks good to me.

**Comment by maelle** [comment]
Just noting that the standard name is `CONTRIBUTING.md`.

**Comment by maelle** [comment]
@krlmlr what downlit fork/branch should one install to knit the README?

**Comment by krlmlr** [comment]
https://github.com/r-lib/downlit/tree/f-readme-document, just merged main, haven't tested yet.
