### ISSUE TITLE
validate_dm vs dm_examine_constraints confusion

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#760]
`validate_dm()` is described in `?dm` as : checks the internal consistency of a dm object. It has only one example which is silent.

`dm_examine_constraints()` is documented on a page titled  "Validate your data model", and its aim is well described.

``` r
library(dm)
dm <- dm_nycflights13()
validate_dm(dm) # no output
dm_examine_constraints(dm)
#> ! Unsatisfied constraints:
#> • Table `flights`: foreign key `tailnum` into table `planes`: values of `flights$tailnum` not in `planes$tailnum`: N725MQ (6), N537MQ (5), N722MQ (5), N730MQ (5), N736MQ (5), …
```

* Shouldn't `validate_dm()` fail there ? If not do we need `dm_has_valid_constraints()` ? There is no simple way to check than `any(!dm_validate_constraints(dm)$is_key)` atm afaict
* Should we clarify the difference between these 2 functions? maybe they could be documented on the same page ?
* We might also mention them in https://krlmlr.github.io/dm/articles/tech-dm-low-level.html

**Comment by krlmlr** [comment]
The purpose of `validate_dm()` is to check the low-level structure of a dm object. Maybe it should be called `dm_validate()` instead, or even with a better name. Do we even need to export it? This function is very different from `dm_examine_constraints()` .

**Comment by krlmlr** [comment]
Unexporting `validate_dm()` in 0.3.0.
