### ISSUE TITLE
How about `append_dm_to()`?

### ISSUE THREAD

**Issue by asiripanich** [cynkra/dm#764]
Hello, thanks for this great package. I was wondering if there is an interest in implementing an `append_dm_to()` function that's basically similar to `copy_dm_to()` but without returning an error if the tables in a new dm object already exist in the destination database? 

Happy to contribute!

**Comment by krlmlr** [comment]
Thanks. Would `dm_rows_insert()` help achieve what you're looking for?

(Sorry for the slow mlfit progress -- I'll get to it at some point.)

**Comment by asiripanich** [comment]
Ahh! we already have `dm_rows_insert()`. How could I forget that! :) 

However, wouldn't something like `copy_dm_to()` be more efficient since it doesn't need to create temporary tables (like `dm_rows_insert()`) before appending to an existing database? Or am I misunderstanding something here?

**Comment by krlmlr** [comment]
I'd like to keep `copy_dm_to()` as is, it is mostly intended to copy to temporary tables.

It is also surprisingly difficult to get both correct and fast table loads from R, in particular if we want consistency across database backends. This is why `dm_rows_insert()` takes the safe route here. For faster loads I think a home-grown `map2()` is the solution for now. We might reconsider once DBI or dbi3 gets table loading right.

**Comment by asiripanich** [comment]
I see, thanks for a clear explanation. :)
