### ISSUE TITLE
db_schema_ functions not working with MSSQL

### ISSUE THREAD

**Issue by Ben-Cox** [cynkra/dm#815]
`db_schema_create()` successfully creates a new schema in my MSSQL database, but then `db_schema_list()`, `db_schema_exists()`, and `db_schema_drop()` don't find it. I can see the schema and tables in management studio and read tables in it with `DBI::dbReadTable(con,Id(schema="foo",table="bar"))`.  `db_schema_list()` is only returning the `db_owner` schema.

**Comment by krlmlr** [comment]
Thanks. I think `db_schema_drop()` should not call `db_schema_exists()` . Does it work when you call ```dm:::`db_schema_drop.Microsoft SQL Server`(...)``` ?

As for the other generics, failure to list the schema could be a permission problem. We don't use an `AUTHORIZATION` clause in the `CREATE SCHEMA` SQL, perhaps you can use `ALTER AUTHORIZATION` or issue a manual `CREATE SCHEMA ... AUTHORIZATION` call to make it work?

**Comment by krlmlr** [comment]
Does #771 fix the problem? Can you please try with `devtools::install_github("cynkra/dm#771")` ?

**Comment by Ben-Cox** [comment]
I will try it out today. I'll edit the comment here with results. Thanks!

**Comment by krlmlr** [comment]
Thanks for confirming!
