### ISSUE TITLE
Consistent API for new functions

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#817]
Needed for  #223

There is a lot to say, so sorry for writing a lot.

I'll try to be as terse as I can and answer in several parts so we can fold some as resolved for clarity. 

We discuss : 

* nest/pack functions' naming (the most urgent part)
* renaming dm_wrap()
* dm level function based on `reunite_parent_child()`
* dm level function based on `decompose_table()`
* dm level dm_flatten_to_tbl()
* changes to the nest/pack API for consistency

## review of the naming conventions

We can separate dm's functions by suffix :

* `dm_verb_tbl()` : `dm_add_tbl()`, `dm_rm_tbl()`, 
  `dm_mutate_tbl()`, `dm_select_tbl()`, `dm_rename_tbl()`
  `dm_nest_tbl()`, `dm_unnest_tbl()`, `dm_pack_tbl()`, `dm_unpack_tbl()`, 
   (unexported: `dm_patch_tbl()`),
* `dm_verb()` (with dplyr verbs): `dm_filter()`, `dm_mutate()`, `dm_select()`
* `dm_verb_to_tbl()` : `dm_apply_filters_to_tbl()`, `dm_flatten_to_tbl()`, 
  `dm_join_to_tbl()`, `dm_squash_to_tbl()`
  
These correspond to categories of behaviours :

* `dm_verb_tbl()` : These functions target a table and change the dm's prototype, 
they might or might not modify tables. The only counter example might be `dm_patch_tbl()` which doesn't restructure the dm per say, but it replaces the tables entirely so can still be
considered a "dm" op rather than a table op. Anyway it is unexported so consistency is less
important there.
* `dm_verb()` : These functions target a table in the dm, and modify it without affecting
  the structure of the dm
* `dm_verb_to_tbl()`: These functions all return a tibble

The functions `reunite_parent_child()` and `decompose_table()` don't follow these formats,
but we want the analogues that take and return a dm to follow a consistent api.

**Comment by moodymudskipper** [comment]
## should we rename new nest/pack functions ?

Since these do a join should we mention the join ?
To me, looking at the dm structure level, we are nesting a table into another,
so talking about "join" is not necessarily useful, it's an implementation detail.
Just like `dm_mutate_tbl()` and `dm_select_tbl()` don't really do dplyr style
mutating not selection, `dm_nest_tbl()` doesn't do dplyr style nesting. 
A function `dm_nest()` would nest a specific table.

If we do want to change the names we have a problem of symetry :
* `dm_nest_join_tbl()` / `dm_unnest_tbl()` don't look like inverse functions

We might do :
* `dm_nest_join_tbl()` / `dm_unjoin_nested_tbl()`

Another issue is that we keep being confused about parents and children, so
it might be useful to mention it in the name, this has the added advantage
of being more easily understood as a dm level operation :

* `dm_nest_child_tbl()` / `dm_unnest_child_tbl()`
* `dm_nest_join_child_tbl()` / `dm_unjoin_nested_child_tbl()` 

All in all, my first choice would be : 
* `dm_nest_child_tbl()` / `dm_unnest_child_tbl()` / `dm_pack_parent_tbl()` / `dm_pack_parent_tbl()`

And my second choice would be to keep as it is.

**Comment by moodymudskipper** [comment]
## Should `dw_wrap()` be renamed to `dm_wrap_tbl()`

Following my categorization at the top, `dw_wrap()` should be `dm_wrap_tbl()`,
we are targetting a table and restructuring the dm. A function named `dm_wrap()`
would be expected not to affect the dm's ptype.

**Comment by moodymudskipper** [comment]
## `dm_join_parent_tbl()` as a dm level `reunite_parent_child()`

`reunite_parent_child()` is the inverse of `decompose_table()`, taking the 2 tables in separate
arguments, it is basically a left join that drops the keys, it also takes an unquoted key that needs to be the same on both sides. 

A dm level function would join by keys, so the notion of left/right/inner/outer might be confusing and I believe tweaking the behavior might better be done by additional explicitly named args. 

I propose : 

```{r}
dm_join_parent_tbl <- function( # or just `dm_join_tbl()`
  dm, 
  parent_table,        # tidy select, a single table
  child_tables = NULL, # tidy select, all children tables by default
  add_unused_parent_keys = FALSE,  # whether to update child so it has all parent keys 
  rm_keys = TRUE,                  # 
  rm_unmatched_keys = FALSE,       # if no referential integrity, whether to remove rows from child
  remove = is.null(child_tables)   # whether to remove the parent table from the dm
)
```

This way we keep a nice symetry `dm_join_parent_tbl()` / `dm_unjoin_parent_tbl()`.

These being dm restructuring operations, so they don't have to be mirrors of
dplyr functions, just like our `dm_mutate_tbl()` isn't.

We had `reunite_parent_child(child_table, parent_table, id_column)`, with the child arg first,
but to be consistent with our pack/nest functions, we should have the table to be absorbed
given before the absorbing table. This allows us to have an optional 3rd argument, which we allow to take several tables (all children by default).  In this case we repeat information from the chosen parent in all child tables.
This solves some circularity issues and is something we should do in our nest/pack functions for consistency.

**Comment by moodymudskipper** [comment]
## `dm_unjoin_parent_tbl()` as a dm level `decompose_table()`

`decompose_table()` creates a list of 2 tables with a common id.

```{r}
# decompose_table(<.data>, <new_id_column>, <...columns to be extracted...>)
decompose_table(mtcars, new_id, am, gear, carb)
```

I propose two versions, the second one uses a prototype, which is consistent with
the pack/nest functions but we need to be able to
easily design one (with #, #) for it to be practical.

```{r, eval = FALSE}
# no prototype
dm_unjoin_parent_tbl <- function( # or dm_unjoin_tbl
  dm, 
  child_tables, # tidyselect, tables to unjoin from
  parent_cols,  # tidyselect, columns to select, need to be named the same across child tables
  parent_name = "new_parent", 
  id = paste0(parent_name, "_id") # id column to be created
) 
  
# with prototype, this mirrors exactly the API of our unnest/unpack functions
dm_unjoin_parent_tbl <- function( # or dm_unjoin_tbl
  dm, 
  child_tables, # tidyselect, tables to unjoin from
  cols,         # tidyselect, columns to select, need to be named the same across child tables
  ptype        # prototype containing the relationships to be created, this covers the parent's name and id name
)
```

**Comment by moodymudskipper** [comment]
## dm level `dm_flatten_to_tbl()`

`dm_flatten_to_tbl()` and `dm_squash_to_tbl()` are recursive invocations of `reunite_parent_child()`
(recursive joins). 
The difference between both verbs is not clear to me and not illustrated in examples, so I'll just
comment about `dm_flatten_to_tbl()`.

In a sense they are similar to current `dm_wrap()`, except that `dm_wrap()` creates a one table dm (or tries to, if `strict = FALSE`).

@krlmr suggests we might retire `dm_flatten_to_tbl()` and `dm_squash_to_tbl()`, 
the alternative would be to have `dm_wrap_to_tbl()` for consistency.

I personally am confused with the quantity of functions in {dm} and it seems to
me that if we implement the dm level functions,
pulling the only table from a dm might not deserve its own function, so as far as I'm concerned they may go.

Above I argued `dm_wrap()` might be renamed to `dm_wrap_tbl()`, since it targets a
table and changes the ptype. The same applies here so I believe we want `dm_flatten_tbl()`

I propose :

```{r}
dm_flatten <- function(
  dm, 
  root,          # tidy select, single table to flatten `tables` into
  tables = NULL, # tidy select, tables to flatten
  strict = is.null(tables), # consistent with dm_wrap, we fail by default if we cannot flatten the full dm
  repair_pk = FALSE
)
```

I name the argument `root` here like in `dm_wrap()`, we might keep `start`
and change `dm_wrap()` since `start` has been there for longer, but to me `root`
is more evocative that `start` for a recursive action for which we might feel that
the "start" is the leaf and not the root.

**Comment by moodymudskipper** [comment]
## Redesigning API of nest/pack/wrap functions for consistency

### `dm_pack_tbl()` and `dm_nest_tbl()`

currently they both have a signature : `f(dm, table, into = NULL)`

consistently with `dm_join_parent_tbl()` we might be able to solve cycle by packing/nesting in each
child/parent. We add also other arguments to remove the key and how to deal with unmatched keys.

```{r}
dm_pack_parent_tbl <- function(
  dm, 
  parent_table,        # renamed `table` arg
  child_tables = NULL, # renamed `into` arg and expanded feature
  add_unused_parent_keys = FALSE,     # from `dm_join_parent_tbl()`
  rm_keys = FALSE,                    # from `dm_join_parent_tbl()`
  rm_unmatched_keys = FALSE,          # from `dm_join_parent_tbl()`
  rm_parent = is.null(child_tables)   # from `dm_join_parent_tbl()`
)
```

```{r}
dm_nest_child_tbl <- function(
  dm, 
  child_table,          # renamed `table` arg
  parent_tables = NULL, # renamed `into` arg and expanded feature
  add_absent_parent_keys = FALSE,     # whether to update parent in case of corrupted relationships
  rm_keys = FALSE,                    # whether to remove the keys
  reduce_parent = FALSE,              # whether to remove rows if some parent keys were not used by child
  rm_child = is.null(child_tables)    # whether to remove the parent table from the dm
)
```

### `dm_unpack_tbl()` and `dm_unnest_tbl()`

The `table` argument becomes `child_tables` for consistency with `dm_unjoin_parent_tbl()`,
this means we can unpack several columns from several children into one parent.

```{r}
dm_unpack_parent_tbl <- function( # or dm_unjoin_tbl
  dm, 
  child_tables, # renamed and expanded feature
  col,          # instead of `cols` in `dm_unjoin_parent_tbl()`
  ptype         
)
```

Similarly we can unnest a child from several parents :

```{r}
dm_unnest_child_tbl <- function( # or dm_unjoin_tbl
  dm, 
  parent_tables, # renamed and expanded feature
  col,           # instead of `cols` in `dm_unjoin_parent_tbl()`
  ptype         
)
```

### `dm_wrap()` 

Already similar to the above `dm_flatten_tbl()` proposal, it would need to gain the new args for consistency : 

```{r}
dm_wrap <- function(
  dm, 
  root,          
  tables = NULL, # new
  strict = is.null(tables) # consistent with dm_wrap, we fail by default if we cannot flatten the full dm
  rm_keys = TRUE,                 # new
  rm_unmatched_keys = FALSE,      # new
  add_absent_parent_keys = FALSE, # new
  reduce_parent = FALSE,          # new
)
```

**Comment by krlmlr** [comment]
I'll take this on in the afternoon.

**Comment by moodymudskipper** [comment]
We went for singular names, we'll see in time how we might extend to multiple tables.

**Comment by krlmlr** [comment]
Closing for now, please open a new issue if still relevant.
