### ISSUE TITLE
More progress bars

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#835]
- [ ] `dm_wrap_tbl()`
- [ ] `dm_unwrap_tbl()`
- [ ] `dm_apply_filters()`

**Comment by moodymudskipper** [comment]
needs #752

**Comment by moodymudskipper** [comment]
@krlmlr given that `dm_apply_filters()` is deprecated, should it be modified to get the feature ? 
It would be small work but not sure if it's good practice to update a deprecated function.
