### ISSUE TITLE
dm_wrap_tbl() fails if column and table have the same name

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#864]
``` r
library(dm)
library(tibble)

dm(a = tibble(b = integer()), b = tibble(b = integer())) %>%
  dm_add_fk(a, b, b, b) %>%
  dm_wrap_tbl(a)
#> New names:
#> * b -> b...1
#> * b -> b...2
#> Error in `check_join_vars()`:
#> ! Join columns must be present in data.
#> x Problem with `b`.
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This seems to be a useful naming scheme. @moodymudskipper: what would it take to support this?

**Comment by moodymudskipper** [comment]
There was a FIXME in pack_join :) 

    # FIXME: handle potential conflict between name_var and existing variables
