### ISSUE TITLE
`json_pack_join()` and `json_nest_join()`

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#917]
For #913

A wrapper around nest_join()

**Comment by krlmlr** [comment]
I though about `jest_join()` and `jack_join()`, but "jest" sounds very frustrating.

Let's go with something that we can later globally search+replace, e.g. `json_nest_join()` and `json_pack_join()`, until we figure out a better naming.

**Comment by TSchiefer** [comment]
what about `nest_jsoin()` and `pack_jsoin()`? ;)
