### ISSUE TITLE
`json_pack.tbl_lazy()`, `json_nest.tbl_lazy()`

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#969]
Related to #913 and #918 

@krlmlr I'm happy to take it but if I do I'd appreciate a bit of guidance 

* Should this live in {dm} or {dbplyr} ? (or be moved later)
* Do we want to support every dbplyr supported DBMS or only those who support json ?
* Is there an existing function that would work better as a base to build on ? AFAICT we need a 'tbl_lazy' method but also `op_json_pack()` etc on the lazy side, and  `sql_render.json_pack_query()` and more on the collect side

**Comment by krlmlr** [comment]
- We'll implement here and move later as necessary.
- Let's start with SQL Server and Postgres, and raise an error for the others.
- The logic here will be very similar to a `transmute()` (or `mutate() %>% select()`) operation. Can we model from these verbs, or perhaps simply forward to them for now?

@mgirlich: would you like to share advice on implementing `json_nest()` and `json_pack()` in a way that makes it possible to later port to dbplyr if needed?

**Comment by mgirlich** [comment]
I'm not sure how the SQL looks like in SQL Server but I quickly hacked something in Postgres

```sql
select json_agg(row_to_json(row(<col1>, <col2>, ...)))
```

This would allow for a relatively simple implementation


```r
dbplyr::lazy_frame(x1 = 1:3, x2 = 4:6, x3 = 7:9, y = 1:3, con = simulate_postgres()) %>% 
  json_pack.tbl_lazy(x = c(x1, x2, x3), y = y)

json_pack.tbl_lazy <- function(.data, ..., .names_sep = NULL) {
  dots <- exprs(...)
  pack_cols <- purrr::map(dots, ~ tidyselect::eval_select(.x, dbplyr::simulate_vars(.data)))
  
  sql_exprs <- purrr::map(pack_cols, ~ sql_json_pack(dbplyr::remote_con(.data), names(.x)))
  
  .data %>% 
    transmute(!!!sql_exprs)
}

sql_json_pack <- function(con, cols) {
  UseMethod("sql_json_pack")
}

sql_json_pack.PqConnection <- function(con, cols) {
  cols <- dbplyr::ident(cols)
  dbplyr::translate_sql(json_agg(row_to_json(row(!!cols))), con = con)
}
```
