### ISSUE TITLE
Some unexported functions are not called by any other function

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#979]
```
"abort_key_constraints_need_db"  "abort_no_src_or_con"           
"abort_temp_table_requested"     "abort_unnamed_table_list"      
"abort_wrong_col_names"          "class_to_db_class"             
"dm_test_load"                   "get_db_table_names"          
"nest_join_zoomed_dm"            "sql_schema_table_list_mssql"   
"sql_schema_table_list_postgres"
```

Most or all of them have tests written for them too, are they still useful ?

**Comment by krlmlr** [comment]
How did you come up with that list? I see `sql_schema_table_list_postgres()` is used in tests.

I wonder if we can parse the full coverage results (running against all backends) to determine functions that aren't called by any test.
