### ISSUE TITLE
igraph 1.3.x compatibility Windows

### ISSUE THREAD

**Issue by jobeid** [cynkra/dm#989]
running R 4.2, dm version 2.8, igraph version 1.3. When calling library(dm), I get an error dialog:

rsession-utf8.exe - Entry Point Not Found
---------------------------
The procedure entry point quadmath_snprintf could not be located in the dynamic link library C:\Users\USERNAME\AppData\Local\R\win-library\4.2\igraph\libs\x64\igraph.dll. 

Reinstalling igraph v1.2 fixes the problem, but I presume this will need to be addressed for future igraph compatibility.
Is anyone else getting that?

**Comment by krlmlr** [comment]
Thanks, good to know. Can you please file an issue at https://github.com/igraph/rigraph/issues? There is little we can do here.

**Comment by krlmlr** [comment]
Now discussed in igraph.
