### ISSUE TITLE
Remove all calls of soft deprecated functionalities

### ISSUE THREAD

**Issue by pawelru** [cynkra/dm#999]
an example:
https://github.com/cynkra/dm/blob/0cd852445b5e41fcc93fc2f428bf02c22d2cc165/vignettes/tech-dm-join.Rmd#L98-L100

results the following:
![image](https://user-images.githubusercontent.com/12943682/169556872-3d39aeed-7560-4b7d-92a8-8b6c9a19979e.png)

Looking into the code - there are more soft-deprecated functions. Would be worth to clean this up.

**Comment by krlmlr** [comment]
Thanks, good catch. Would you like to help out with a PR?
